import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Regulations } from './../entities/regulations.entity';
import { RegulationsCountries } from '../entities/regulations-countries.entity';

@Injectable()
export class SeedService {
    constructor(
        @InjectRepository(RegulationsCountries)
        private regulationsCountriesRepository: Repository<RegulationsCountries>,

        @InjectRepository(Regulations)
        private regulationsRepository: Repository<Regulations>,
    ) { }

    async seedRegulationsCountries() {
        const countriesArabic = [
            {
                iso: 'AF',
                printableName: 'أفغانستان',
                phonePrefix: '93',
                nationality: 'أفغاني',
            },
            {
                iso: 'AX',
                printableName: 'جزر آلاند',
                phonePrefix: '358',
                nationality: 'ألاندي',
            },
            {
                iso: 'AL',
                printableName: 'ألبانيا',
                phonePrefix: '355',
                nationality: 'ألباني',
            },
            {
                iso: 'DZ',
                printableName: 'الجزائر',
                phonePrefix: '213',
                nationality: 'جزائري',
            },
            {
                iso: 'AS',
                printableName: 'ساموا الأمريكية',
                phonePrefix: '684',
                nationality: 'ساموي أمريكي',
            },
            {
                iso: 'AD',
                printableName: 'أندورا',
                phonePrefix: '376',
                nationality: 'أندوري',
            },
            {
                iso: 'AO',
                printableName: 'أنغولا',
                phonePrefix: '244',
                nationality: 'أنغولي',
            },
            {
                iso: 'AI',
                printableName: 'أنغويلا',
                phonePrefix: '264',
                nationality: 'أنغويلي',
            },
            {
                iso: 'AQ',
                printableName: 'أنتاركتيكا',
                phonePrefix: '672',
                nationality: '',
            },
            {
                iso: 'AG',
                printableName: 'أنتيغوا وباربودا',
                phonePrefix: '268',
                nationality: 'أنتيغوي، باربودي',
            },
            {
                iso: 'AR',
                printableName: 'الأرجنتين',
                phonePrefix: '54',
                nationality: 'أرجنتيني',
            },
            {
                iso: 'AM',
                printableName: 'أرمينيا',
                phonePrefix: '374',
                nationality: 'أرميني',
            },
            {
                iso: 'AW',
                printableName: 'أروبا',
                phonePrefix: '297',
                nationality: 'أروبي',
            },
            {
                iso: 'AC',
                printableName: 'جزيرة أسنسيون',
                phonePrefix: '247',
                nationality: '',
            },
            {
                iso: 'AU',
                printableName: 'أستراليا',
                phonePrefix: '61',
                nationality: 'أسترالي',
            },
            {
                iso: 'AT',
                printableName: 'النمسا',
                phonePrefix: '43',
                nationality: 'نمساوي',
            },
            {
                iso: 'AZ',
                printableName: 'أذربيجان',
                phonePrefix: '994',
                nationality: 'أذربيجاني',
            },
            {
                iso: 'BS',
                printableName: 'الباهاما',
                phonePrefix: '242',
                nationality: 'باهامي',
            },
            {
                iso: 'BH',
                printableName: 'البحرين',
                phonePrefix: '973',
                nationality: 'بحريني',
            },
            {
                iso: 'BD',
                printableName: 'بنغلاديش',
                phonePrefix: '880',
                nationality: 'بنغلاديشي',
            },
            {
                iso: 'BB',
                printableName: 'بربادوس',
                phonePrefix: '246',
                nationality: 'بربادوسي',
            },
            {
                iso: 'BY',
                printableName: 'بيلاروس',
                phonePrefix: '375',
                nationality: 'بيلاروسي',
            },
            {
                iso: 'BE',
                printableName: 'بلجيكا',
                phonePrefix: '32',
                nationality: 'بلجيكي',
            },
            {
                iso: 'BZ',
                printableName: 'بليز',
                phonePrefix: '501',
                nationality: 'بليزي',
            },
            {
                iso: 'BJ',
                printableName: 'بنين',
                phonePrefix: '229',
                nationality: 'بنيني',
            },
            {
                iso: 'BM',
                printableName: 'برمودا',
                phonePrefix: '441',
                nationality: 'برمودي',
            },
            {
                iso: 'BT',
                printableName: 'بوتان',
                phonePrefix: '975',
                nationality: 'بوتاني',
            },
            {
                iso: 'BO',
                printableName: 'بوليفيا',
                phonePrefix: '591',
                nationality: 'بوليفي',
            },
            {
                iso: 'BQ',
                printableName: 'بونير، سينت أوستاتيوس وسابا',
                phonePrefix: '599',
                nationality: '',
            },
            {
                iso: 'BA',
                printableName: 'البوسنة والهرسك',
                phonePrefix: '387',
                nationality: 'بوسني، هرزي',
            },
            {
                iso: 'BW',
                printableName: 'بوتسوانا',
                phonePrefix: '267',
                nationality: 'بوتسواني',
            },
            {
                iso: 'BV',
                printableName: 'جزيرة بوفيت',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'BR',
                printableName: 'البرازيل',
                phonePrefix: '55',
                nationality: 'برازيلي',
            },
            {
                iso: 'IO',
                printableName: 'إقليم المحيط الهندي البريطاني',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'BN',
                printableName: 'بروناي دار السلام',
                phonePrefix: '673',
                nationality: 'بروناي',
            },
            {
                iso: 'BG',
                printableName: 'بلغاريا',
                phonePrefix: '359',
                nationality: 'بلغاري',
            },
            {
                iso: 'BF',
                printableName: 'بوركينا فاسو',
                phonePrefix: '226',
                nationality: 'بوركيني',
            },
            {
                iso: 'BI',
                printableName: 'بوروندي',
                phonePrefix: '257',
                nationality: 'بوروندي',
            },
            {
                iso: 'KH',
                printableName: 'كمبوديا',
                phonePrefix: '855',
                nationality: 'كمبودي',
            },
            {
                iso: 'CM',
                printableName: 'الكاميرون',
                phonePrefix: '237',
                nationality: 'كاميروني',
            },
            {
                iso: 'CA',
                printableName: 'كندا',
                phonePrefix: '1',
                nationality: 'كندي',
            },
            {
                iso: 'IC',
                printableName: 'جزر الكناري',
                phonePrefix: '928',
                nationality: '',
            },
            // {
            //   iso: 'SX',
            //   printableName: 'جزر الكناري',
            //   phonePrefix: '721',
            //   nationality: '',
            // },
            {
                iso: 'CV',
                printableName: 'الرأس الأخضر',
                phonePrefix: '238',
                nationality: 'الرأس الأخضري',
            },
            {
                iso: 'KY',
                printableName: 'جزر كايمان',
                phonePrefix: '345',
                nationality: 'كايماني',
            },
            {
                iso: 'CF',
                printableName: 'جمهورية أفريقيا الوسطى',
                phonePrefix: '236',
                nationality: 'أفريقي وسطي',
            },
            {
                iso: 'EA',
                printableName: 'سبتة، مليلية',
                phonePrefix: '341',
                nationality: '',
            },
            {
                iso: 'TD',
                printableName: 'تشاد',
                phonePrefix: '235',
                nationality: 'تشادي',
            },
            {
                iso: 'CL',
                printableName: 'تشيلي',
                phonePrefix: '56',
                nationality: 'تشيلي',
            },
            {
                iso: 'CN',
                printableName: 'الصين',
                phonePrefix: '86',
                nationality: 'صيني',
            },

            {
                iso: 'CX',
                printableName: 'جزيرة كريسماس',
                phonePrefix: '61',
                nationality: '',
            },
            {
                iso: 'CP',
                printableName: 'جزيرة كليبرتون',
                phonePrefix: '262',
                nationality: '',
            },
            {
                iso: 'CC',
                printableName: 'جزر كوكوس (كيلينغ)',
                phonePrefix: '61',
                nationality: '',
            },
            {
                iso: 'CO',
                printableName: 'كولومبيا',
                phonePrefix: '57',
                nationality: 'كولومبي',
            },
            {
                iso: 'KM',
                printableName: 'جزر القمر',
                phonePrefix: '269',
                nationality: 'قمري',
            },
            {
                iso: 'CG',
                printableName: 'الكونغو',
                phonePrefix: '242',
                nationality: 'كونغولي',
            },
            {
                iso: 'CD',
                printableName: 'جمهورية الكونغو الديمقراطية',
                phonePrefix: '243',
                nationality: 'كونغولي',
            },
            {
                iso: 'CK',
                printableName: 'جزر كوك',
                phonePrefix: '682',
                nationality: 'كوكي',
            },
            {
                iso: 'CR',
                printableName: 'كوستاريكا',
                phonePrefix: '506',
                nationality: 'كوستاريكي',
            },
            {
                iso: 'CI',
                printableName: 'كوت ديفوار',
                phonePrefix: '225',
                nationality: 'إيفواري',
            },
            {
                iso: 'HR',
                printableName: 'كرواتيا',
                phonePrefix: '385',
                nationality: 'كرواتي',
            },
            {
                iso: 'CU',
                printableName: 'كوبا',
                phonePrefix: '53',
                nationality: 'كوبي',
            },
            {
                iso: 'CW',
                printableName: 'كوراساو',
                phonePrefix: '599',
                nationality: 'كوراساوي',
            },
            {
                iso: 'CY',
                printableName: 'قبرص',
                phonePrefix: '357',
                nationality: 'قبرصي',
            },
            {
                iso: 'CZ',
                printableName: 'جمهورية التشيك',
                phonePrefix: '420',
                nationality: 'تشيكي',
            },
            {
                iso: 'DK',
                printableName: 'الدنمارك',
                phonePrefix: '45',
                nationality: 'دنماركي',
            },
            {
                iso: 'DG',
                printableName: 'دييغو غارسيا',
                phonePrefix: '246',
                nationality: '',
            },
            {
                iso: 'DJ',
                printableName: 'جيبوتي',
                phonePrefix: '253',
                nationality: 'جيبوتي',
            },
            {
                iso: 'DM',
                printableName: 'دومينيكا',
                phonePrefix: '767',
                nationality: 'دومينيكي',
            },
            {
                iso: 'DO',
                printableName: 'جمهورية الدومينيكان',
                phonePrefix: '809',
                nationality: 'دومينيكاني',
            },
            {
                iso: 'EC',
                printableName: 'الإكوادور',
                phonePrefix: '593',
                nationality: 'إكوادوري',
            },
            {
                iso: 'EG',
                printableName: 'مصر',
                phonePrefix: '20',
                nationality: 'مصري',
            },
            {
                iso: 'SV',
                printableName: 'السلفادور',
                phonePrefix: '503',
                nationality: 'سلفادوري',
            },
            {
                iso: 'GQ',
                printableName: 'غينيا الاستوائية',
                phonePrefix: '240',
                nationality: 'غيني استوائي',
            },
            {
                iso: 'ER',
                printableName: 'إريتريا',
                phonePrefix: '291',
                nationality: 'إريتري',
            },
            {
                iso: 'EE',
                printableName: 'إستونيا',
                phonePrefix: '372',
                nationality: 'إستوني',
            },
            {
                iso: 'ET',
                printableName: 'إثيوبيا',
                phonePrefix: '251',
                nationality: 'إثيوبي',
            },
            {
                iso: 'FK',
                printableName: 'جزر فوكلاند',
                phonePrefix: '500',
                nationality: 'فوكلاندي',
            },
            {
                iso: 'FO',
                printableName: 'جزر فارو',
                phonePrefix: '298',
                nationality: 'فاروي',
            },
            {
                iso: 'FJ',
                printableName: 'فيجي',
                phonePrefix: '679',
                nationality: 'فيجي',
            },
            {
                iso: 'FI',
                printableName: 'فنلندا',
                phonePrefix: '358',
                nationality: 'فنلندي',
            },
            {
                iso: 'FR',
                printableName: 'فرنسا',
                phonePrefix: '33',
                nationality: 'فرنسي',
            },
            {
                iso: 'GF',
                printableName: 'غيانا الفرنسية',
                phonePrefix: '594',
                nationality: '',
            },
            {
                iso: 'PF',
                printableName: 'بولينيزيا الفرنسية',
                phonePrefix: '689',
                nationality: '',
            },
            {
                iso: 'TF',
                printableName: 'الأقاليم الجنوبية الفرنسية',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'GA',
                printableName: 'الغابون',
                phonePrefix: '241',
                nationality: 'غابوني',
            },
            {
                iso: 'GM',
                printableName: 'غامبيا',
                phonePrefix: '220',
                nationality: 'غامبي',
            },
            {
                iso: 'GE',
                printableName: 'جورجيا',
                phonePrefix: '995',
                nationality: 'جورجي',
            },
            {
                iso: 'DE',
                printableName: 'ألمانيا',
                phonePrefix: '49',
                nationality: 'ألماني',
            },
            {
                iso: 'GH',
                printableName: 'غانا',
                phonePrefix: '233',
                nationality: 'غاني',
            },
            {
                iso: 'GI',
                printableName: 'جبل طارق',
                phonePrefix: '350',
                nationality: 'جبل طارق',
            },
            {
                iso: 'GR',
                printableName: 'اليونان',
                phonePrefix: '30',
                nationality: 'يوناني',
            },
            {
                iso: 'GL',
                printableName: 'غرينلاند',
                phonePrefix: '299',
                nationality: 'غرينلاندي',
            },
            {
                iso: 'GD',
                printableName: 'غرينادا',
                phonePrefix: '473',
                nationality: 'غرينادي',
            },
            {
                iso: 'GP',
                printableName: 'جوادلوب',
                phonePrefix: '590',
                nationality: '',
            },
            {
                iso: 'GU',
                printableName: 'غوام',
                phonePrefix: '671',
                nationality: 'غوامي',
            },
            {
                iso: 'GT',
                printableName: 'غواتيمالا',
                phonePrefix: '502',
                nationality: 'غواتيمالي',
            },
            {
                iso: 'GG',
                printableName: 'غيرنزي',
                phonePrefix: '44',
                nationality: '',
            },
            {
                iso: 'GN',
                printableName: 'غينيا',
                phonePrefix: '224',
                nationality: 'غيني',
            },
            {
                iso: 'GW',
                printableName: 'غينيا بيساو',
                phonePrefix: '245',
                nationality: 'غيني بيساوي',
            },
            {
                iso: 'GY',
                printableName: 'غيانا',
                phonePrefix: '592',

                nationality: 'غياني',
            },
            {
                iso: 'HT',
                printableName: 'هايتي',
                phonePrefix: '509',
                nationality: 'هايتي',
            },
            {
                iso: 'HM',
                printableName: 'جزيرة هيرد وجزر ماكدونالد',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'VA',
                printableName: 'الكرسي الرسولي (دولة الفاتيكان)',
                phonePrefix: '379',
                nationality: 'فاتيكان',
            },
            {
                iso: 'HN',
                printableName: 'هندوراس',
                phonePrefix: '504',
                nationality: 'هندوراسي',
            },
            {
                iso: 'HK',
                printableName: 'هونغ كونغ',
                phonePrefix: '852',
                nationality: 'هونغ كونغي',
            },
            {
                iso: 'HU',
                printableName: 'المجر',
                phonePrefix: '36',
                nationality: 'مجري',
            },
            {
                iso: 'IS',
                printableName: 'آيسلندا',
                phonePrefix: '354',
                nationality: 'آيسلندي',
            },
            {
                iso: 'IN',
                printableName: 'الهند',
                phonePrefix: '91',
                nationality: 'هندي',
            },
            {
                iso: 'ID',
                printableName: 'إندونيسيا',
                phonePrefix: '62',
                nationality: 'إندونيسي',
            },
            {
                iso: 'IR',
                printableName: 'إيران، جمهورية',
                phonePrefix: '98',
                nationality: 'إيراني',
            },
            {
                iso: 'IQ',
                printableName: 'العراق',
                phonePrefix: '964',
                nationality: 'عراقي',
            },
            {
                iso: 'IE',
                printableName: 'أيرلندا',
                phonePrefix: '353',
                nationality: 'أيرلندي',
            },
            {
                iso: 'IM',
                printableName: 'جزيرة مان',
                phonePrefix: '44',
                nationality: 'مانكسي',
            },
            {
                iso: 'IL',
                printableName: 'إسرائيل',
                phonePrefix: '972',
                nationality: 'إسرائيلي',
            },
            {
                iso: 'IT',
                printableName: 'إيطاليا',
                phonePrefix: '39',
                nationality: 'إيطالي',
            },
            {
                iso: 'JM',
                printableName: 'جامايكا',
                phonePrefix: '876',
                nationality: 'جامايكي',
            },
            {
                iso: 'JP',
                printableName: 'اليابان',
                phonePrefix: '81',
                nationality: 'ياباني',
            },
            {
                iso: 'JE',
                printableName: 'جيرسي',
                phonePrefix: '44',
                nationality: '',
            },
            {
                iso: 'JO',
                printableName: 'الأردن',
                phonePrefix: '962',
                nationality: 'أردني',
            },
            {
                iso: 'KZ',
                printableName: 'كازاخستان',
                phonePrefix: '7',
                nationality: 'كازاخستاني',
            },
            {
                iso: 'KE',
                printableName: 'كينيا',
                phonePrefix: '254',
                nationality: 'كيني',
            },
            {
                iso: 'KI',
                printableName: 'كيريباتي',
                phonePrefix: '686',
                nationality: 'كيريباتي',
            },
            {
                iso: 'KP',
                printableName: 'كوريا، جمهورية',
                phonePrefix: '850',
                nationality: 'كوري شمالي',
            },
            {
                iso: 'KR',
                printableName: 'كوريا الجنوبية',
                phonePrefix: '82',
                nationality: 'كوري جنوبي',
            },
            {
                iso: 'KW',
                printableName: 'الكويت',
                phonePrefix: '965',
                nationality: 'كويتي',
            },
            {
                iso: 'KG',
                printableName: 'قيرغيزستان',
                phonePrefix: '996',
                nationality: 'قيرغيزي',
            },
            {
                iso: 'LA',
                printableName: 'لاوس',
                phonePrefix: '856',
                nationality: 'لاوسي',
            },
            {
                iso: 'LV',
                printableName: 'لاتفيا',
                phonePrefix: '371',
                nationality: 'لاتفي',
            },
            {
                iso: 'LB',
                printableName: 'لبنان',
                phonePrefix: '961',
                nationality: 'لبناني',
            },
            {
                iso: 'LS',
                printableName: 'ليسوتو',
                phonePrefix: '266',
                nationality: 'ليسوتو',
            },
            {
                iso: 'LR',
                printableName: 'ليبيريا',
                phonePrefix: '231',
                nationality: 'ليبيري',
            },
            {
                iso: 'LY',
                printableName: 'ليبيا',
                phonePrefix: '218',
                nationality: 'ليبي',
            },
            {
                iso: 'LI',
                printableName: 'ليختنشتاين',
                phonePrefix: '423',
                nationality: 'ليختنشتايني',
            },
            {
                iso: 'LT',
                printableName: 'ليتوانيا',
                phonePrefix: '370',
                nationality: 'ليتواني',
            },
            {
                iso: 'LU',
                printableName: 'لوكسمبورغ',
                phonePrefix: '352',
                nationality: 'لوكسمبورغي',
            },
            {
                iso: 'MO',
                printableName: 'ماكاو',
                phonePrefix: '853',
                nationality: 'ماكاوي',
            },
            {
                iso: 'MK',
                printableName: 'مقدونيا، الجمهورية اليوغوسلافية السابقة',
                phonePrefix: '389',
                nationality: 'مقدوني',
            },
            {
                iso: 'MG',
                printableName: 'مدغشقر',
                phonePrefix: '261',
                nationality: 'مدغشقري',
            },
            {
                iso: 'MW',
                printableName: 'ملاوي',
                phonePrefix: '265',
                nationality: 'ملاوي',
            },
            {
                iso: 'MY',
                printableName: 'ماليزيا',
                phonePrefix: '60',
                nationality: 'ماليزي',
            },
            {
                iso: 'MV',
                printableName: 'المالديف',
                phonePrefix: '960',
                nationality: 'مالديفي',
            },
            {
                iso: 'ML',
                printableName: 'مالي',
                phonePrefix: '223',
                nationality: 'مالي',
            },
            {
                iso: 'MT',
                printableName: 'مالطا',
                phonePrefix: '356',
                nationality: 'مالطي',
            },
            {
                iso: 'MH',
                printableName: 'جزر مارشال',
                phonePrefix: '692',
                nationality: 'مارشالي',
            },
            {
                iso: 'MQ',
                printableName: 'مارتينيك',
                phonePrefix: '596',
                nationality: '',
            },
            {
                iso: 'MR',
                printableName: 'موريتانيا',
                phonePrefix: '222',
                nationality: 'موريتاني',
            },
            {
                iso: 'MU',
                printableName: 'موريشيوس',
                phonePrefix: '230',
                nationality: 'موريشيوسي',
            },
            {
                iso: 'YT',
                printableName: 'مايوت',
                phonePrefix: '262',
                nationality: '',
            },
            {
                iso: 'MX',
                printableName: 'المكسيك',
                phonePrefix: '52',
                nationality: 'مكسيكي',
            },
            {
                iso: 'FM',
                printableName: 'ولايات ميكرونيزيا المتحدة',
                phonePrefix: '691',
                nationality: 'ميكرونيزي',
            },
            {
                iso: 'MD',
                printableName: 'مولدوفا، جمهورية',
                phonePrefix: '373',
                nationality: 'مولدوفي',
            },
            {
                iso: 'MC',
                printableName: 'موناكو',
                phonePrefix: '377',
                nationality: 'موناكي',
            },
            {
                iso: 'MN',
                printableName: 'منغوليا',
                phonePrefix: '976',
                nationality: 'منغولي',
            },
            {
                iso: 'ME',
                printableName: 'الجبل الأسود',
                phonePrefix: '382',
                nationality: 'مونتينيغري',
            },
            {
                iso: 'MS',
                printableName: 'مونتسيرات',
                phonePrefix: '664',
                nationality: 'مونتسيراتي',
            },
            {
                iso: 'MA',
                printableName: 'المغرب',
                phonePrefix: '212',
                nationality: 'مغربي',
            },
            {
                iso: 'MZ',
                printableName: 'موزمبيق',
                phonePrefix: '258',
                nationality: 'موزمبيقي',
            },
            {
                iso: 'MM',
                printableName: 'ميانمار',
                phonePrefix: '95',
                nationality: 'بورمي',
            },
            {
                iso: 'NA',
                printableName: 'ناميبيا',
                phonePrefix: '264',
                nationality: 'ناميبي',
            },
            {
                iso: 'NR',
                printableName: 'ناورو',
                phonePrefix: '674',
                nationality: 'ناوروي',
            },
            {
                iso: 'NP',
                printableName: 'نيبال',
                phonePrefix: '977',
                nationality: 'نيبالي',
            },
            {
                iso: 'NL',
                printableName: 'هولندا',
                phonePrefix: '31',
                nationality: 'هولندي',
            },
            {
                iso: 'NC',
                printableName: 'كاليدونيا الجديدة',
                phonePrefix: '687',
                nationality: 'كاليدوني جديد',
            },
            {
                iso: 'NZ',
                printableName: 'نيوزيلندا',
                phonePrefix: '64',
                nationality: 'نيوزيلندي',
            },
            {
                iso: 'NI',
                printableName: 'نيكاراغوا',
                phonePrefix: '505',
                nationality: 'نيكاراغوي',
            },
            {
                iso: 'NE',
                printableName: 'النيجر',
                phonePrefix: '227',
                nationality: 'نيجيري',
            },
            {
                iso: 'NG',
                printableName: 'نيجيريا',
                phonePrefix: '234',
                nationality: 'نيجيري',
            },
            {
                iso: 'NU',
                printableName: 'نيوي',
                phonePrefix: '683',
                nationality: 'نيوي',
            },
            {
                iso: 'NF',
                printableName: 'جزيرة نورفولك',
                phonePrefix: '672',
                nationality: '',
            },
            {
                iso: 'MP',
                printableName: 'جزر ماريانا الشمالية',
                phonePrefix: '670',
                nationality: 'مارياني شمالي',
            },
            {
                iso: 'NO',
                printableName: 'النرويج',
                phonePrefix: '47',
                nationality: 'نرويجي',
            },
            {
                iso: 'OM',
                printableName: 'عمان',
                phonePrefix: '968',
                nationality: 'عماني',
            },
            {
                iso: 'PK',
                printableName: 'باكستان',
                phonePrefix: '92',
                nationality: 'باكستاني',
            },
            {
                iso: 'PW',
                printableName: 'بالاو',
                phonePrefix: '680',
                nationality: 'بالاوي',
            },
            {
                iso: 'PS',
                printableName: 'الأراضي الفلسطينية المحتلة',
                phonePrefix: '970',
                nationality: 'فلسطيني',
            },
            {
                iso: 'PA',
                printableName: 'بنما',
                phonePrefix: '507',
                nationality: 'بنمي',
            },
            {
                iso: 'PG',
                printableName: 'بابوا غينيا الجديدة',
                phonePrefix: '675',
                nationality: 'بابوا غيني جديد',
            },
            {
                iso: 'PY',
                printableName: 'باراغواي',
                phonePrefix: '595',
                nationality: 'باراغواياني',
            },
            {
                iso: 'PE',
                printableName: 'بيرو',
                phonePrefix: '51',
                nationality: 'بيري',
            },
            {
                iso: 'PH',
                printableName: 'الفلبين',
                phonePrefix: '63',
                nationality: 'فلبيني',
            },
            {
                iso: 'PN',
                printableName: 'بيتكيرن',
                phonePrefix: '870',
                nationality: '',
            },
            {
                iso: 'PL',
                printableName: 'بولندا',
                phonePrefix: '48',
                nationality: 'بولندي',
            },
            {
                iso: 'PT',
                printableName: 'البرتغال',
                phonePrefix: '351',
                nationality: 'برتغالي',
            },
            {
                iso: 'PR',
                printableName: 'بورتوريكو',
                phonePrefix: '1',
                nationality: 'بورتوريكي',
            },
            {
                iso: 'QA',
                printableName: 'قطر',
                phonePrefix: '974',
                nationality: 'قطري',
            },
            {
                iso: 'RE',
                printableName: 'ريونيون',
                phonePrefix: '262',
                nationality: '',
            },
            {
                iso: 'RO',
                printableName: 'رومانيا',
                phonePrefix: '40',
                nationality: 'روماني',
            },
            {
                iso: 'RU',
                printableName: 'روسيا الاتحادية',
                phonePrefix: '7',
                nationality: 'روسي',
            },
            {
                iso: 'RW',
                printableName: 'رواندا',
                phonePrefix: '250',
                nationality: 'رواندي',
            },
            {
                iso: 'BL',
                printableName: 'سان بارتيلمي',
                phonePrefix: '590',
                nationality: '',
            },
            {
                iso: 'SH',
                printableName: 'سانت هيلينا، أسينسيون وتريستان دا كونها',
                phonePrefix: '290',
                nationality: '',
            },
            {
                iso: 'KN',
                printableName: 'سانت كيتس ونيفيس',
                phonePrefix: '1',
                nationality: 'كيتسي، نيفيسي',
            },
            {
                iso: 'LC',
                printableName: 'سانت لوسيا',
                phonePrefix: '1',
                nationality: 'لوسياني',
            },
            {
                iso: 'MF',
                printableName: 'سانت مارتن (الجزء الفرنسي)',
                phonePrefix: '590',
                nationality: '',
            },
            {
                iso: 'PM',
                printableName: 'سان بيير وميكلون',
                phonePrefix: '508',
                nationality: '',
            },
            {
                iso: 'VC',
                printableName: 'سانت فنسنت وجزر غرينادين',
                phonePrefix: '1',
                nationality: 'فنسنتي',
            },
            {
                iso: 'WS',
                printableName: 'ساموا',
                phonePrefix: '685',
                nationality: 'ساموي',
            },
            {
                iso: 'SM',
                printableName: 'سان مارينو',
                phonePrefix: '378',
                nationality: 'ماريني',
            },
            {
                iso: 'ST',
                printableName: 'ساو تومي وبرينسيبي',
                phonePrefix: '239',
                nationality: 'ساو تومي وبرينسيبي',
            },
            {
                iso: 'SA',
                printableName: 'المملكة العربية السعودية',
                phonePrefix: '966',
                nationality: 'سعودي',
            },
            {
                iso: 'SN',
                printableName: 'السنغال',
                phonePrefix: '221',
                nationality: 'سنغالي',
            },
            {
                iso: 'RS',
                printableName: 'صربيا',
                phonePrefix: '381',
                nationality: 'صربي',
            },
            {
                iso: 'SC',
                printableName: 'سيشيل',
                phonePrefix: '248',
                nationality: 'سيشلي',
            },
            {
                iso: 'SL',
                printableName: 'سيراليون',
                phonePrefix: '232',
                nationality: 'سيراليوني',
            },
            {
                iso: 'SG',
                printableName: 'سنغافورة',
                phonePrefix: '65',
                nationality: 'سنغافوري',
            },
            {
                iso: 'SX',
                printableName: 'سينت مارتن (الجزء الهولندي)',
                phonePrefix: '1',
                nationality: '',
            },
            {
                iso: 'SK',
                printableName: 'سلوفاكيا',
                phonePrefix: '421',
                nationality: 'سلوفاكي',
            },
            {
                iso: 'SI',
                printableName: 'سلوفينيا',
                phonePrefix: '386',
                nationality: 'سلوفيني',
            },
            {
                iso: 'SB',
                printableName: 'جزر سليمان',
                phonePrefix: '677',
                nationality: 'سليماني',
            },
            {
                iso: 'SO',
                printableName: 'الصومال',
                phonePrefix: '252',
                nationality: 'صومالي',
            },
            {
                iso: 'ZA',
                printableName: 'جنوب أفريقيا',
                phonePrefix: '27',
                nationality: 'جنوب أفريقي',
            },
            {
                iso: 'GS',
                printableName: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
                phonePrefix: '500',
                nationality: '',
            },
            {
                iso: 'SS',
                printableName: 'جنوب السودان',
                phonePrefix: '211',
                nationality: 'جنوب سوداني',
            },
            {
                iso: 'ES',
                printableName: 'إسبانيا',
                phonePrefix: '34',
                nationality: 'إسباني',
            },
            {
                iso: 'LK',
                printableName: 'سريلانكا',
                phonePrefix: '94',
                nationality: 'سريلانكي',
            },
            {
                iso: 'SD',
                printableName: 'السودان',
                phonePrefix: '249',
                nationality: 'سوداني',
            },
            {
                iso: 'SR',
                printableName: 'سورينام',
                phonePrefix: '597',
                nationality: 'سورينامي',
            },
            {
                iso: 'SJ',
                printableName: 'سفالبارد ويان ماين',
                phonePrefix: '47',
                nationality: '',
            },
            {
                iso: 'SZ',
                printableName: 'إسواتيني',
                phonePrefix: '268',
                nationality: 'سواتيني',
            },
            {
                iso: 'SE',
                printableName: 'السويد',
                phonePrefix: '46',
                nationality: 'سويدي',
            },
            {
                iso: 'CH',
                printableName: 'سويسرا',
                phonePrefix: '41',
                nationality: 'سويسري',
            },
            {
                iso: 'SY',
                printableName: 'الجمهورية العربية السورية',
                phonePrefix: '963',
                nationality: 'سوري',
            },
            {
                iso: 'TW',
                printableName: 'تايوان، مقاطعة الصين',
                phonePrefix: '886',
                nationality: 'تايواني',
            },
            {
                iso: 'TJ',
                printableName: 'طاجيكستان',
                phonePrefix: '992',
                nationality: 'طاجيكستاني',
            },
            {
                iso: 'TZ',
                printableName: 'جمهورية تنزانيا المتحدة',
                phonePrefix: '255',
                nationality: 'تنزاني',
            },
            {
                iso: 'TH',
                printableName: 'تايلاند',
                phonePrefix: '66',
                nationality: 'تايلاندي',
            },
            {
                iso: 'TL',
                printableName: 'تيمور الشرقية',
                phonePrefix: '670',
                nationality: 'تيموري',
            },
            {
                iso: 'TG',
                printableName: 'توغو',
                phonePrefix: '228',
                nationality: 'توغولي',
            },
            {
                iso: 'TK',
                printableName: 'توكيلاو',
                phonePrefix: '690',
                nationality: '',
            },
            {
                iso: 'TO',
                printableName: 'تونغا',
                phonePrefix: '676',
                nationality: 'تونغي',
            },
            {
                iso: 'TT',
                printableName: 'ترينيداد وتوباغو',
                phonePrefix: '1',
                nationality: 'ترينيدادي، توباغوني',
            },
            {
                iso: 'TN',
                printableName: 'تونس',
                phonePrefix: '216',
                nationality: 'تونسي',
            },
            {
                iso: 'TR',
                printableName: 'تركيا',
                phonePrefix: '90',
                nationality: 'تركي',
            },
            {
                iso: 'TM',
                printableName: 'تركمانستان',
                phonePrefix: '993',
                nationality: 'تركماني',
            },
            {
                iso: 'TC',
                printableName: 'جزر توركس وكايكوس',
                phonePrefix: '1',
                nationality: '',
            },
            {
                iso: 'TV',
                printableName: 'توفالو',
                phonePrefix: '688',
                nationality: 'توفالي',
            },
            {
                iso: 'UG',
                printableName: 'أوغندا',
                phonePrefix: '256',
                nationality: 'أوغندي',
            },
            {
                iso: 'UA',
                printableName: 'أوكرانيا',
                phonePrefix: '380',
                nationality: 'أوكراني',
            },
            {
                iso: 'AE',
                printableName: 'الإمارات العربية المتحدة',
                phonePrefix: '971',
                nationality: 'إماراتي',
            },
            {
                iso: 'GB',
                printableName: 'المملكة المتحدة',
                phonePrefix: '44',
                nationality: 'بريطاني',
            },
            {
                iso: 'US',
                printableName: 'الولايات المتحدة الأمريكية',
                phonePrefix: '1',
                nationality: 'أمريكي',
            },
            {
                iso: 'UY',
                printableName: 'أوروغواي',
                phonePrefix: '598',
                nationality: 'أوروغواياني',
            },
            {
                iso: 'UZ',
                printableName: 'أوزبكستان',
                phonePrefix: '998',
                nationality: 'أوزبكي',
            },
            {
                iso: 'VU',
                printableName: 'فانواتو',
                phonePrefix: '678',
                nationality: 'فانواتي',
            },
            {
                iso: 'VE',
                printableName: 'فنزويلا، جمهورية',
                phonePrefix: '58',
                nationality: 'فنزويلي',
            },
            {
                iso: 'VN',
                printableName: 'فيتنام',
                phonePrefix: '84',
                nationality: 'فيتنامي',
            },
            {
                iso: 'VG',
                printableName: 'جزر العذراء البريطانية',
                phonePrefix: '1',
                nationality: 'بريطاني فيرجيني',
            },
            {
                iso: 'VI',
                printableName: 'جزر العذراء الأمريكية',
                phonePrefix: '1',
                nationality: 'أمريكي فيرجيني',
            },
            {
                iso: 'WF',
                printableName: 'واليس وفوتونا',
                phonePrefix: '681',
                nationality: '',
            },
            {
                iso: 'EH',

                printableName: 'الصحراء الغربية',
                phonePrefix: '212',
                nationality: 'صحراوي',
            },
            {
                iso: 'YE',
                printableName: 'اليمن',
                phonePrefix: '967',
                nationality: 'يمني',
            },
            {
                iso: 'ZM',
                printableName: 'زامبيا',
                phonePrefix: '260',
                nationality: 'زامبي',
            },
            {
                iso: 'ZW',
                printableName: 'زيمبابوي',
                phonePrefix: '263',
                nationality: 'زيمبابوي',
            },

        ];


        const countriesEnglish = [

            {
                iso: 'AF',
                printableName: 'Afghanistan',
                phonePrefix: '93',
                nationality: 'Afghan',
            },
            {
                iso: 'AX',
                printableName: 'Aland Islands',
                phonePrefix: '358',
                nationality: 'Alandic',
            },
            {
                iso: 'AL',
                printableName: 'Albania',
                phonePrefix: '355',
                nationality: 'Albanian',
            },
            {
                iso: 'DZ',
                printableName: 'Algeria',
                phonePrefix: '213',
                nationality: 'Algerian',
            },
            {
                iso: 'AS',
                printableName: 'American Samoa',
                phonePrefix: '684',
                nationality: 'American Samoan',
            },
            {
                iso: 'AD',
                printableName: 'Andorra',
                phonePrefix: '376',
                nationality: 'Andorran',
            },
            {
                iso: 'AO',
                printableName: 'Angola',
                phonePrefix: '244',
                nationality: 'Angolan',
            },
            {
                iso: 'AI',
                printableName: 'Anguilla',
                phonePrefix: '264',
                nationality: 'Anguillan',
            },
            {
                iso: 'AQ',
                printableName: 'Antarctica',
                phonePrefix: '672',
                nationality: '',
            },
            {
                iso: 'AG',
                printableName: 'Antigua and Barbuda',
                phonePrefix: '268',
                nationality: 'Antiguan, Barbudan',
            },
            {
                iso: 'AR',
                printableName: 'Argentina',
                phonePrefix: '54',
                nationality: 'Argentinian',
            },
            {
                iso: 'AM',
                printableName: 'Armenia',
                phonePrefix: '374',
                nationality: 'Armenian',
            },
            {
                iso: 'AW',
                printableName: 'Aruba',
                phonePrefix: '297',
                nationality: 'Aruban',
            },
            {
                iso: 'AC',
                printableName: 'Ascension Island',
                phonePrefix: '247',
                nationality: '',
            },
            {
                iso: 'AU',
                printableName: 'Australia',
                phonePrefix: '61',
                nationality: 'Australian',
            },
            {
                iso: 'AT',
                printableName: 'Austria',
                phonePrefix: '43',
                nationality: 'Austrian',
            },
            {
                iso: 'AZ',
                printableName: 'Azerbaijan',
                phonePrefix: '994',
                nationality: 'Azerbaijani',
            },
            {
                iso: 'BS',
                printableName: 'Bahamas',
                phonePrefix: '242',
                nationality: 'Bahamian',
            },
            {
                iso: 'BH',
                printableName: 'Bahrain',
                phonePrefix: '973',
                nationality: 'Bahraini',
            },
            {
                iso: 'BD',
                printableName: 'Bangladesh',
                phonePrefix: '880',
                nationality: 'Bangladeshi',
            },
            {
                iso: 'BB',
                printableName: 'Barbados',
                phonePrefix: '246',
                nationality: 'Barbadian',
            },
            {
                iso: 'BY',
                printableName: 'Belarus',
                phonePrefix: '375',
                nationality: 'Belarusian',
            },
            {
                iso: 'BE',
                printableName: 'Belgium',
                phonePrefix: '32',
                nationality: 'Belgian',
            },
            {
                iso: 'BZ',
                printableName: 'Belize',
                phonePrefix: '501',
                nationality: 'Belizean',
            },
            {
                iso: 'BJ',
                printableName: 'Benin',
                phonePrefix: '229',
                nationality: 'Beninese',
            },
            {
                iso: 'BM',
                printableName: 'Bermuda',
                phonePrefix: '441',
                nationality: 'Bermudian',
            },
            {
                iso: 'BT',
                printableName: 'Bhutan',
                phonePrefix: '975',
                nationality: 'Bhutanese',
            },
            {
                iso: 'BO',
                printableName: 'Bolivia',
                phonePrefix: '591',
                nationality: 'Bolivian',
            },
            {
                iso: 'BQ',
                printableName: 'Bonaire, Sint Eustatius and Saba',
                phonePrefix: '599',
                nationality: '',
            },
            {
                iso: 'BA',
                printableName: 'Bosnia and Herzegovina',
                phonePrefix: '387',
                nationality: 'Bosnian, Herzegovinian',
            },
            {
                iso: 'BW',
                printableName: 'Botswana',
                phonePrefix: '267',
                nationality: 'Motswana',
            },
            {
                iso: 'BV',
                printableName: 'Bouvet Island',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'BR',
                printableName: 'Brazil',
                phonePrefix: '55',
                nationality: 'Brazilian',
            },
            {
                iso: 'IO',
                printableName: 'British Indian Ocean Territory',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'BN',
                printableName: 'Brunei Darussalam',
                phonePrefix: '673',
                nationality: 'Bruneian',
            },
            {
                iso: 'BG',
                printableName: 'Bulgaria',
                phonePrefix: '359',
                nationality: 'Bulgarian',
            },
            {
                iso: 'BF',
                printableName: 'Burkina Faso',
                phonePrefix: '226',
                nationality: 'Burkinabe',
            },
            {
                iso: 'BI',
                printableName: 'Burundi',
                phonePrefix: '257',
                nationality: 'Burundian',
            },
            {
                iso: 'KH',
                printableName: 'Cambodia',
                phonePrefix: '855',
                nationality: 'Cambodian',
            },
            {
                iso: 'CM',
                printableName: 'Cameroon',
                phonePrefix: '237',
                nationality: 'Cameroonian',
            },
            {
                iso: 'CA',
                printableName: 'Canada',
                phonePrefix: '1',
                nationality: 'Canadian',
            },
            {
                iso: 'IC',
                printableName: 'Canary Islands',
                phonePrefix: '928',
                nationality: '',
            },
            // {
            //   iso: 'SX',
            //   printableName: 'Canary Islands',
            //   phonePrefix: '721',
            //   nationality: '',
            // },
            {
                iso: 'CV',
                printableName: 'Cape Verde',
                phonePrefix: '238',
                nationality: 'Cape Verdean',
            },
            {
                iso: 'KY',
                printableName: 'Cayman Islands',
                phonePrefix: '345',
                nationality: 'Caymanian',
            },
            {
                iso: 'CF',
                printableName: 'Central African Republic',
                phonePrefix: '236',
                nationality: 'Central African',
            },
            {
                iso: 'EA',
                printableName: 'Ceuta, Melilla',
                phonePrefix: '341',
                nationality: '',
            },
            {
                iso: 'TD',
                printableName: 'Chad',
                phonePrefix: '235',
                nationality: 'Chadian',
            },
            {
                iso: 'CL',
                printableName: 'Chile',
                phonePrefix: '56',
                nationality: 'Chilean',
            },
            {
                iso: 'CN',
                printableName: 'China',
                phonePrefix: '86',
                nationality: 'Chinese',
            },
            {
                iso: 'CX',
                printableName: 'Christmas Island',
                phonePrefix: '61',
                nationality: '',
            },
            {
                iso: 'CP',
                printableName: 'Clipperton Island',
                phonePrefix: '262',
                nationality: '',
            },
            {
                iso: 'CC',
                printableName: 'Cocos (Keeling) Islands',
                phonePrefix: '61',
                nationality: '',
            },
            {
                iso: 'CO',
                printableName: 'Colombia',
                phonePrefix: '57',
                nationality: 'Colombian',
            },
            {
                iso: 'KM',
                printableName: 'Comoros',
                phonePrefix: '269',
                nationality: 'Comoran',
            },
            {
                iso: 'CG',
                printableName: 'Congo',
                phonePrefix: '242',
                nationality: 'Congolese',
            },
            {
                iso: 'CD',
                printableName: 'Congo, Democratic Republic of the',
                phonePrefix: '243',
                nationality: 'Congolese',
            },
            {
                iso: 'CK',
                printableName: 'Cook Islands',
                phonePrefix: '682',
                nationality: 'Cook Islander',
            },
            {
                iso: 'CR',
                printableName: 'Costa Rica',
                phonePrefix: '506',
                nationality: 'Costa Rican',
            },
            {
                iso: 'CI',
                printableName: "Cote d'Ivoire",
                phonePrefix: '225',
                nationality: 'Ivorian',
            },
            {
                iso: 'HR',
                printableName: 'Croatia',
                phonePrefix: '385',
                nationality: 'Croatian',
            },
            {
                iso: 'CU',
                printableName: 'Cuba',
                phonePrefix: '53',
                nationality: 'Cuban',
            },
            {
                iso: 'CW',
                printableName: 'Curacao',
                phonePrefix: '599',
                nationality: 'Curacaoan',
            },
            {
                iso: 'CY',
                printableName: 'Cyprus',
                phonePrefix: '357',
                nationality: 'Cypriot',
            },
            {
                iso: 'CZ',
                printableName: 'Czech Republic',
                phonePrefix: '420',
                nationality: 'Czech',
            },
            {
                iso: 'DK',
                printableName: 'Denmark',
                phonePrefix: '45',
                nationality: 'Danish',
            },
            {
                iso: 'DG',
                printableName: 'Diego Garcia',
                phonePrefix: '246',
                nationality: '',
            },
            {
                iso: 'DJ',
                printableName: 'Djibouti',
                phonePrefix: '253',
                nationality: 'Djiboutian',
            },
            {
                iso: 'DM',
                printableName: 'Dominica',
                phonePrefix: '767',
                nationality: 'Dominican',
            },
            {
                iso: 'DO',
                printableName: 'Dominican Republic',
                phonePrefix: '809',
                nationality: 'Dominican',
            },
            {
                iso: 'EC',
                printableName: 'Ecuador',
                phonePrefix: '593',
                nationality: 'Ecuadorian',
            },
            {
                iso: 'EG',
                printableName: 'Egypt',
                phonePrefix: '20',
                nationality: 'Egyptian',
            },
            {
                iso: 'SV',
                printableName: 'El Salvador',
                phonePrefix: '503',
                nationality: 'Salvadoran',
            },
            {
                iso: 'GQ',
                printableName: 'Equatorial Guinea',
                phonePrefix: '240',
                nationality: 'Equatorial Guinean',
            },
            {
                iso: 'ER',
                printableName: 'Eritrea',
                phonePrefix: '291',
                nationality: 'Eritrean',
            },
            {
                iso: 'EE',
                printableName: 'Estonia',
                phonePrefix: '372',
                nationality: 'Estonian',
            },
            {
                iso: 'ET',
                printableName: 'Ethiopia',
                phonePrefix: '251',
                nationality: 'Ethiopian',
            },
            {
                iso: 'FK',
                printableName: 'Falkland Islands (Malvinas)',
                phonePrefix: '500',
                nationality: 'Falkland Islander',
            },
            {
                iso: 'FO',
                printableName: 'Faroe Islands',
                phonePrefix: '298',
                nationality: 'Faroese',
            },
            {
                iso: 'FJ',
                printableName: 'Fiji',
                phonePrefix: '679',
                nationality: 'Fijian',
            },
            {
                iso: 'FI',
                printableName: 'Finland',
                phonePrefix: '358',
                nationality: 'Finnish',
            },
            {
                iso: 'FR',
                printableName: 'France',
                phonePrefix: '33',
                nationality: 'French',
            },
            {
                iso: 'GF',
                printableName: 'French Guiana',
                phonePrefix: '594',
                nationality: '',
            },
            {
                iso: 'PF',
                printableName: 'French Polynesia',
                phonePrefix: '689',
                nationality: '',
            },
            {
                iso: 'TF',
                printableName: 'French Southern Territories',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'GA',
                printableName: 'Gabon',
                phonePrefix: '241',
                nationality: 'Gabonese',
            },
            {
                iso: 'GM',
                printableName: 'Gambia',
                phonePrefix: '220',
                nationality: 'Gambian',
            },
            {
                iso: 'GE',
                printableName: 'Georgia',
                phonePrefix: '995',
                nationality: 'Georgian',
            },
            {
                iso: 'DE',
                printableName: 'Germany',
                phonePrefix: '49',
                nationality: 'German',
            },
            {
                iso: 'GH',
                printableName: 'Ghana',
                phonePrefix: '233',
                nationality: 'Ghanaian',
            },
            {
                iso: 'GI',
                printableName: 'Gibraltar',
                phonePrefix: '350',
                nationality: 'Gibraltar',
            },
            {
                iso: 'GR',
                printableName: 'Greece',
                phonePrefix: '30',
                nationality: 'Greek',
            },
            {
                iso: 'GL',
                printableName: 'Greenland',
                phonePrefix: '299',
                nationality: 'Greenlandic',
            },
            {
                iso: 'GD',
                printableName: 'Grenada',
                phonePrefix: '473',
                nationality: 'Grenadian',
            },
            {
                iso: 'GP',
                printableName: 'Guadeloupe',
                phonePrefix: '590',
                nationality: '',
            },
            {
                iso: 'GU',
                printableName: 'Guam',
                phonePrefix: '671',
                nationality: 'Guamanian',
            },
            {
                iso: 'GT',
                printableName: 'Guatemala',
                phonePrefix: '502',
                nationality: 'Guatemalan',
            },
            {
                iso: 'GG',
                printableName: 'Guernsey',
                phonePrefix: '44',
                nationality: '',
            },
            {
                iso: 'GN',
                printableName: 'Guinea',
                phonePrefix: '224',
                nationality: 'Guinean',
            },
            {
                iso: 'GW',
                printableName: 'Guinea-Bissau',
                phonePrefix: '245',
                nationality: 'Guinean-Bissau',
            },
            {
                iso: 'GY',
                printableName: 'Guyana',
                phonePrefix: '592',
                nationality: 'Guyanese',
            },
            {
                iso: 'HT',
                printableName: 'Haiti',
                phonePrefix: '509',
                nationality: 'Haitian',
            },
            {
                iso: 'HM',
                printableName: 'Heard Island and McDonald Islands',
                phonePrefix: '000',
                nationality: '',
            },
            {
                iso: 'VA',
                printableName: 'Holy See (Vatican City State)',
                phonePrefix: '379',
                nationality: 'Vatican',
            },
            {
                iso: 'HN',
                printableName: 'Honduras',
                phonePrefix: '504',
                nationality: 'Honduran',
            },
            {
                iso: 'HK',
                printableName: 'Hong Kong',
                phonePrefix: '852',
                nationality: 'Hong Konger',
            },
            {
                iso: 'HU',
                printableName: 'Hungary',
                phonePrefix: '36',
                nationality: 'Hungarian',
            },
            {
                iso: 'IS',
                printableName: 'Iceland',
                phonePrefix: '354',
                nationality: 'Icelander',
            },
            {
                iso: 'IN',
                printableName: 'India',
                phonePrefix: '91',
                nationality: 'Indian',
            },
            {
                iso: 'ID',
                printableName: 'Indonesia',
                phonePrefix: '62',
                nationality: 'Indonesian',
            },
            {
                iso: 'IR',
                printableName: 'Iran, Islamic Republic of',
                phonePrefix: '98',
                nationality: 'Iranian',
            },
            {
                iso: 'IQ',
                printableName: 'Iraq',
                phonePrefix: '964',
                nationality: 'Iraqi',
            },
            {
                iso: 'IE',
                printableName: 'Ireland',
                phonePrefix: '353',
                nationality: 'Irish',
            },
            {
                iso: 'IM',
                printableName: 'Isle of Man',
                phonePrefix: '44',
                nationality: 'Manx',
            },
            {
                iso: 'IL',
                printableName: 'Israel',
                phonePrefix: '972',
                nationality: 'Israeli',
            },
            {
                iso: 'IT',
                printableName: 'Italy',
                phonePrefix: '39',
                nationality: 'Italian',
            },
            {
                iso: 'JM',
                printableName: 'Jamaica',
                phonePrefix: '876',
                nationality: 'Jamaican',
            },
            {
                iso: 'JP',
                printableName: 'Japan',
                phonePrefix: '81',
                nationality: 'Japanese',
            },
            {
                iso: 'JE',
                printableName: 'Jersey',
                phonePrefix: '44',
                nationality: '',
            },
            {
                iso: 'JO',
                printableName: 'Jordan',
                phonePrefix: '962',
                nationality: 'Jordanian',
            },
            {
                iso: 'KZ',
                printableName: 'Kazakhstan',
                phonePrefix: '7',
                nationality: 'Kazakhstani',
            },
            {
                iso: 'KE',
                printableName: 'Kenya',
                phonePrefix: '254',
                nationality: 'Kenyan',
            },
            {
                iso: 'KI',
                printableName: 'Kiribati',
                phonePrefix: '686',
                nationality: 'I-Kiribati',
            },
            {
                iso: 'KP',
                printableName: "Korea, Democratic People's Republic of",
                phonePrefix: '850',
                nationality: 'North Korean',
            },
            {
                iso: 'KR',
                printableName: 'Korea, Republic of',
                phonePrefix: '82',
                nationality: 'South Korean',
            },
            {
                iso: 'KW',
                printableName: 'Kuwait',
                phonePrefix: '965',
                nationality: 'Kuwaiti',
            },
            {
                iso: 'KG',
                printableName: 'Kyrgyzstan',
                phonePrefix: '996',
                nationality: 'Kyrgyzstani',
            },
            {
                iso: 'LA',
                printableName: "Lao People's Democratic Republic",
                phonePrefix: '856',
                nationality: 'Laotian',
            },
            {
                iso: 'LV',
                printableName: 'Latvia',
                phonePrefix: '371',
                nationality: 'Latvian',
            },
            {
                iso: 'LB',
                printableName: 'Lebanon',
                phonePrefix: '961',
                nationality: 'Lebanese',
            },
            {
                iso: 'LS',
                printableName: 'Lesotho',
                phonePrefix: '266',
                nationality: 'Mosotho',
            },
            {
                iso: 'LR',
                printableName: 'Liberia',
                phonePrefix: '231',
                nationality: 'Liberian',
            },
            {
                iso: 'LY',
                printableName: 'Libya',
                phonePrefix: '218',
                nationality: 'Libyan',
            },
            {
                iso: 'LI',
                printableName: 'Liechtenstein',
                phonePrefix: '423',
                nationality: 'Liechtensteiner',
            },
            {
                iso: 'LT',
                printableName: 'Lithuania',
                phonePrefix: '370',
                nationality: 'Lithuanian',
            },
            {
                iso: 'LU',
                printableName: 'Luxembourg',
                phonePrefix: '352',
                nationality: 'Luxembourger',
            },
            {
                iso: 'MO',
                printableName: 'Macao',
                phonePrefix: '853',
                nationality: 'Macanese',
            },
            {
                iso: 'MK',
                printableName: 'Macedonia, the former Yugoslav Republic of',
                phonePrefix: '389',
                nationality: 'Macedonian',
            },
            {
                iso: 'MG',
                printableName: 'Madagascar',
                phonePrefix: '261',
                nationality: 'Malagasy',
            },
            {
                iso: 'MW',
                printableName: 'Malawi',
                phonePrefix: '265',
                nationality: 'Malawian',
            },
            {
                iso: 'MY',
                printableName: 'Malaysia',
                phonePrefix: '60',
                nationality: 'Malaysian',
            },
            {
                iso: 'MV',
                printableName: 'Maldives',
                phonePrefix: '960',
                nationality: 'Maldivian',
            },
            {
                iso: 'ML',
                printableName: 'Mali',
                phonePrefix: '223',
                nationality: 'Malian',
            },
            {
                iso: 'MT',
                printableName: 'Malta',
                phonePrefix: '356',
                nationality: 'Maltese',
            },
            {
                iso: 'MH',
                printableName: 'Marshall Islands',
                phonePrefix: '692',
                nationality: 'Marshallese',
            },
            {
                iso: 'MQ',
                printableName: 'Martinique',
                phonePrefix: '596',
                nationality: '',
            },
            {
                iso: 'MR',
                printableName: 'Mauritania',
                phonePrefix: '222',
                nationality: 'Mauritanian',
            },
            {
                iso: 'MU',
                printableName: 'Mauritius',
                phonePrefix: '230',
                nationality: 'Mauritian',
            },
            {
                iso: 'YT',
                printableName: 'Mayotte',
                phonePrefix: '262',
                nationality: '',
            },
            {
                iso: 'MX',
                printableName: 'Mexico',
                phonePrefix: '52',
                nationality: 'Mexican',
            },
            {
                iso: 'FM',
                printableName: 'Micronesia, Federated States of',
                phonePrefix: '691',
                nationality: 'Micronesian',
            },
            {
                iso: 'MD',
                printableName: 'Moldova, Republic of',
                phonePrefix: '373',
                nationality: 'Moldovan',
            },
            {
                iso: 'MC',
                printableName: 'Monaco',
                phonePrefix: '377',
                nationality: 'Monacan',
            },
            {
                iso: 'MN',
                printableName: 'Mongolia',
                phonePrefix: '976',
                nationality: 'Mongolian',
            },
            {
                iso: 'ME',
                printableName: 'Montenegro',
                phonePrefix: '382',
                nationality: 'Montenegrin',
            },
            {
                iso: 'MS',
                printableName: 'Montserrat',
                phonePrefix: '664',
                nationality: 'Montserratian',
            },
            {
                iso: 'MA',
                printableName: 'Morocco',
                phonePrefix: '212',
                nationality: 'Moroccan',
            },
            {
                iso: 'MZ',
                printableName: 'Mozambique',
                phonePrefix: '258',
                nationality: 'Mozambican',
            },
            {
                iso: 'MM',
                printableName: 'Myanmar',
                phonePrefix: '95',
                nationality: 'Burmese',
            },
            {
                iso: 'NA',
                printableName: 'Namibia',
                phonePrefix: '264',
                nationality: 'Namibian',
            },
            {
                iso: 'NR',
                printableName: 'Nauru',
                phonePrefix: '674',
                nationality: 'Nauruan',
            },
            {
                iso: 'NP',
                printableName: 'Nepal',
                phonePrefix: '977',
                nationality: 'Nepalese',
            },
            {
                iso: 'NL',
                printableName: 'Netherlands',
                phonePrefix: '31',
                nationality: 'Dutch',
            },
            {
                iso: 'NC',
                printableName: 'New Caledonia',
                phonePrefix: '687',
                nationality: 'New Caledonian',
            },
            {
                iso: 'NZ',
                printableName: 'New Zealand',
                phonePrefix: '64',
                nationality: 'New Zealander',
            },
            {
                iso: 'NI',
                printableName: 'Nicaragua',
                phonePrefix: '505',
                nationality: 'Nicaraguan',
            },
            {
                iso: 'NE',
                printableName: 'Niger',
                phonePrefix: '227',
                nationality: 'Nigerien',
            },
            {
                iso: 'NG',
                printableName: 'Nigeria',
                phonePrefix: '234',
                nationality: 'Nigerian',
            },
            {
                iso: 'NU',
                printableName: 'Niue',
                phonePrefix: '683',
                nationality: 'Niuean',
            },
            {
                iso: 'NF',
                printableName: 'Norfolk Island',
                phonePrefix: '672',
                nationality: '',
            },
            {
                iso: 'MP',
                printableName: 'Northern Mariana Islands',
                phonePrefix: '670',
                nationality: 'Northern Mariana Islander',
            },
            {
                iso: 'NO',
                printableName: 'Norway',
                phonePrefix: '47',
                nationality: 'Norwegian',
            },
            {
                iso: 'OM',
                printableName: 'Oman',
                phonePrefix: '968',
                nationality: 'Omani',
            },
            {
                iso: 'PK',
                printableName: 'Pakistan',
                phonePrefix: '92',
                nationality: 'Pakistani',
            },
            {
                iso: 'PW',
                printableName: 'Palau',
                phonePrefix: '680',
                nationality: 'Palauan',
            },
            {
                iso: 'PS',
                printableName: 'Palestinian Territory, Occupied',
                phonePrefix: '970',
                nationality: 'Palestinian',
            },
            {
                iso: 'PA',
                printableName: 'Panama',
                phonePrefix: '507',
                nationality: 'Panamanian',
            },
            {
                iso: 'PG',
                printableName: 'Papua New Guinea',
                phonePrefix: '675',
                nationality: 'Papua New Guinean',
            },
            {
                iso: 'PY',
                printableName: 'Paraguay',
                phonePrefix: '595',
                nationality: 'Paraguayan',
            },
            {
                iso: 'PE',
                printableName: 'Peru',
                phonePrefix: '51',
                nationality: 'Peruvian',
            },
            {
                iso: 'PH',
                printableName: 'Philippines',
                phonePrefix: '63',
                nationality: 'Filipino',
            },
            {
                iso: 'PN',
                printableName: 'Pitcairn',
                phonePrefix: '870',
                nationality: '',
            },
            {
                iso: 'PL',
                printableName: 'Poland',
                phonePrefix: '48',
                nationality: 'Polish',
            },
            {
                iso: 'PT',
                printableName: 'Portugal',
                phonePrefix: '351',
                nationality: 'Portuguese',
            },
            {
                iso: 'PR',
                printableName: 'Puerto Rico',
                phonePrefix: '1',
                nationality: 'Puerto Rican',
            },
            {
                iso: 'QA',
                printableName: 'Qatar',
                phonePrefix: '974',
                nationality: 'Qatari',
            },
            {
                iso: 'RE',
                printableName: 'Reunion',
                phonePrefix: '262',
                nationality: '',
            },
            {
                iso: 'RO',
                printableName: 'Romania',
                phonePrefix: '40',
                nationality: 'Romanian',
            },
            {
                iso: 'RU',
                printableName: 'Russian Federation',
                phonePrefix: '7',
                nationality: 'Russian',
            },
            {
                iso: 'RW',
                printableName: 'Rwanda',
                phonePrefix: '250',
                nationality: 'Rwandan',
            },
            {
                iso: 'BL',
                printableName: 'Saint Barthelemy',
                phonePrefix: '590',
                nationality: '',
            },
            {
                iso: 'SH',
                printableName: 'Saint Helena, Ascension and Tristan da Cunha',
                phonePrefix: '290',
                nationality: '',
            },
            {
                iso: 'KN',
                printableName: 'Saint Kitts and Nevis',
                phonePrefix: '1',
                nationality: 'Kittitian, Nevisian',
            },
            {
                iso: 'LC',
                printableName: 'Saint Lucia',
                phonePrefix: '1',
                nationality: 'Saint Lucian',
            },
            {
                iso: 'MF',
                printableName: 'Saint Martin (French part)',
                phonePrefix: '590',
                nationality: '',
            },
            {
                iso: 'PM',
                printableName: 'Saint Pierre and Miquelon',
                phonePrefix: '508',
                nationality: '',
            },
            {
                iso: 'VC',
                printableName: 'Saint Vincent and the Grenadines',
                phonePrefix: '1',
                nationality: 'Saint Vincentian',
            },
            {
                iso: 'WS',
                printableName: 'Samoa',
                phonePrefix: '685',
                nationality: 'Samoan',
            },
            {
                iso: 'SM',
                printableName: 'San Marino',
                phonePrefix: '378',
                nationality: 'San Marinese',
            },
            {
                iso: 'ST',
                printableName: 'Sao Tome and Principe',
                phonePrefix: '239',
                nationality: 'Sao Tomean',
            },
            {
                iso: 'SA',
                printableName: 'Saudi Arabia',
                phonePrefix: '966',
                nationality: 'Saudi Arabian',
            },
            {
                iso: 'SN',
                printableName: 'Senegal',
                phonePrefix: '221',
                nationality: 'Senegalese',
            },
            {
                iso: 'RS',
                printableName: 'Serbia',
                phonePrefix: '381',
                nationality: 'Serbian',
            },
            {
                iso: 'SC',
                printableName: 'Seychelles',
                phonePrefix: '248',
                nationality: 'Seychellois',
            },
            {
                iso: 'SL',
                printableName: 'Sierra Leone',
                phonePrefix: '232',
                nationality: 'Sierra Leonean',
            },
            {
                iso: 'SG',
                printableName: 'Singapore',
                phonePrefix: '65',
                nationality: 'Singaporean',
            },
            {
                iso: 'SX',
                printableName: 'Sint Maarten (Dutch part)',
                phonePrefix: '1',
                nationality: '',
            },
            {
                iso: 'SK',
                printableName: 'Slovakia',
                phonePrefix: '421',
                nationality: 'Slovak',
            },
            {
                iso: 'SI',
                printableName: 'Slovenia',
                phonePrefix: '386',
                nationality: 'Slovenian',
            },
            {
                iso: 'SB',
                printableName: 'Solomon Islands',
                phonePrefix: '677',
                nationality: 'Solomon Islander',
            },
            {
                iso: 'SO',
                printableName: 'Somalia',
                phonePrefix: '252',
                nationality: 'Somali',
            },
            {
                iso: 'ZA',
                printableName: 'South Africa',
                phonePrefix: '27',
                nationality: 'South African',
            },
            {
                iso: 'GS',
                printableName: 'South Georgia and the South Sandwich Islands',
                phonePrefix: '500',
                nationality: '',
            },
            {
                iso: 'SS',
                printableName: 'South Sudan',
                phonePrefix: '211',
                nationality: 'South Sudanese',
            },
            {
                iso: 'ES',
                printableName: 'Spain',
                phonePrefix: '34',
                nationality: 'Spanish',
            },
            {
                iso: 'LK',
                printableName: 'Sri Lanka',
                phonePrefix: '94',
                nationality: 'Sri Lankan',
            },
            {
                iso: 'SD',
                printableName: 'Sudan',
                phonePrefix: '249',
                nationality: 'Sudanese',
            },
            {
                iso: 'SR',
                printableName: 'Suriname',
                phonePrefix: '597',
                nationality: 'Surinamese',
            },
            {
                iso: 'SJ',
                printableName: 'Svalbard and Jan Mayen',
                phonePrefix: '47',
                nationality: '',
            },
            {
                iso: 'SZ',
                printableName: 'Swaziland',
                phonePrefix: '268',
                nationality: 'Swazi',
            },
            {
                iso: 'SE',
                printableName: 'Sweden',
                phonePrefix: '46',
                nationality: 'Swedish',
            },
            {
                iso: 'CH',
                printableName: 'Switzerland',
                phonePrefix: '41',
                nationality: 'Swiss',
            },
            {
                iso: 'SY',
                printableName: 'Syrian Arab Republic',
                phonePrefix: '963',
                nationality: 'Syrian',
            },
            {
                iso: 'TW',
                printableName: 'Taiwan, Province of China',
                phonePrefix: '886',
                nationality: 'Taiwanese',
            },
            {
                iso: 'TJ',
                printableName: 'Tajikistan',
                phonePrefix: '992',
                nationality: 'Tajikistani',
            },
            {
                iso: 'TZ',
                printableName: 'Tanzania, United Republic of',
                phonePrefix: '255',
                nationality: 'Tanzanian',
            },
            {
                iso: 'TH',
                printableName: 'Thailand',
                phonePrefix: '66',
                nationality: 'Thai',
            },
            {
                iso: 'TL',
                printableName: 'Timor-Leste',
                phonePrefix: '670',
                nationality: 'Timorese',
            },
            {
                iso: 'TG',
                printableName: 'Togo',
                phonePrefix: '228',
                nationality: 'Togolese',
            },
            {
                iso: 'TK',
                printableName: 'Tokelau',
                phonePrefix: '690',
                nationality: '',
            },
            {
                iso: 'TO',
                printableName: 'Tonga',
                phonePrefix: '676',
                nationality: 'Tongan',
            },
            {
                iso: 'TT',
                printableName: 'Trinidad and Tobago',
                phonePrefix: '1',
                nationality: 'Trinidadian, Tobagonian',
            },
            {
                iso: 'TN',
                printableName: 'Tunisia',
                phonePrefix: '216',
                nationality: 'Tunisian',
            },
            {
                iso: 'TR',
                printableName: 'Turkey',
                phonePrefix: '90',
                nationality: 'Turkish',
            },
            {
                iso: 'TM',
                printableName: 'Turkmenistan',
                phonePrefix: '993',
                nationality: 'Turkmen',
            },
            {
                iso: 'TC',
                printableName: 'Turks and Caicos Islands',
                phonePrefix: '1',
                nationality: '',
            },
            {
                iso: 'TV',
                printableName: 'Tuvalu',
                phonePrefix: '688',
                nationality: 'Tuvaluan',
            },
            {
                iso: 'UG',
                printableName: 'Uganda',
                phonePrefix: '256',
                nationality: 'Ugandan',
            },
            {
                iso: 'UA',
                printableName: 'Ukraine',
                phonePrefix: '380',
                nationality: 'Ukrainian',
            },
            {
                iso: 'AE',
                printableName: 'United Arab Emirates',
                phonePrefix: '971',
                nationality: 'Emirati',
            },
            {
                iso: 'GB',
                printableName: 'United Kingdom',
                phonePrefix: '44',
                nationality: 'British',
            },
            {
                iso: 'US',
                printableName: 'United States Of America',
                phonePrefix: '1',
                nationality: 'American',
            },
            {
                iso: 'UY',
                printableName: 'Uruguay',
                phonePrefix: '598',
                nationality: 'Uruguayan',
            },
            {
                iso: 'UZ',
                printableName: 'Uzbekistan',
                phonePrefix: '998',
                nationality: 'Uzbekistani',
            },
            {
                iso: 'VU',
                printableName: 'Vanuatu',
                phonePrefix: '678',
                nationality: 'Ni-Vanuatu',
            },
            {
                iso: 'VE',
                printableName: 'Venezuela, Bolivarian Republic of',
                phonePrefix: '58',
                nationality: 'Venezuelan',
            },
            {
                iso: 'VN',
                printableName: 'Viet Nam',
                phonePrefix: '84',
                nationality: 'Vietnamese',
            },
            {
                iso: 'VG',
                printableName: 'Virgin Islands, British',
                phonePrefix: '1',
                nationality: 'British Virgin Islander',
            },
            {
                iso: 'VI',
                printableName: 'Virgin Islands, U.S.',
                phonePrefix: '1',
                nationality: 'U.S. Virgin Islander',
            },
            {
                iso: 'WF',
                printableName: 'Wallis and Futuna',
                phonePrefix: '681',
                nationality: '',
            },
            {
                iso: 'EH',
                printableName: 'Western Sahara',
                phonePrefix: '212',
                nationality: 'Sahrawi',
            },
            {
                iso: 'YE',
                printableName: 'Yemen',
                phonePrefix: '967',
                nationality: 'Yemeni',
            },
            {
                iso: 'ZM',
                printableName: 'Zambia',
                phonePrefix: '260',
                nationality: 'Zambian',
            },
            {
                iso: 'ZW',
                printableName: 'Zimbabwe',
                phonePrefix: '263',
                nationality: 'Zimbabwean',
            },
        ];

        // Find or create the corresponding regulation record
        const regulation = await this.regulationsRepository.findOne({ where: { name: 'Your Regulation Name' } });

        if (!regulation) {
            console.error('Regulation not found');
            return;
        }

        // Insert Arabic data
        for (const country of countriesArabic) {
            await this.regulationsCountriesRepository.save({
                regulation,
                countryCode: country.iso,
                isBlocked: true, // set to true if needed
            });
        }

        // Insert English data
        for (const country of countriesEnglish) {
            await this.regulationsCountriesRepository.save({
                regulation,
                countryCode: country.iso,
                isBlocked: true, // set to true if needed
            });
        }

        console.log('Data seeding completed');
    }
}
