import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { PartnerType } from 'src/admin/custom-dropdown/custom-dropdown/entities/partner-type.entity';
import { I18nContext } from 'nestjs-i18n';

@Injectable()
export class SettingsService {
  constructor(
    @InjectRepository(PartnerType)
    private readonly partnerTypeRepository: Repository<PartnerType>,
  ) {}
  getCountriesIso(lang?: string) {
    const i18n = I18nContext.current();
    const ar = lang?.toUpperCase() ??  i18n?.lang.toLocaleUpperCase();
    if (ar === 'AR') {
      return {
        result: [
          {
            iso: 'AF',
            printableName: 'أفغانستان',
            phonePrefix: '93',
            nationality: 'أفغاني',
            capital: 'كابل',
          },
          {
            iso: 'AX',
            printableName: 'جزر آلاند',
            phonePrefix: '358',
            nationality: 'ألاندي',
            capital: 'ماريهامن',
          },
          {
            iso: 'AL',
            printableName: 'ألبانيا',
            phonePrefix: '355',
            nationality: 'ألباني',
            capital: 'تيرانا',
          },
          {
            iso: 'DZ',
            printableName: 'الجزائر',
            phonePrefix: '213',
            nationality: 'جزائري',
            capital: 'الجزائر',
          },
          {
            iso: 'AS',
            printableName: 'ساموا الأمريكية',
            phonePrefix: '684',
            nationality: 'ساموي أمريكي',
            capital: 'باغو باغو',
          },
          {
            iso: 'AD',
            printableName: 'أندورا',
            phonePrefix: '376',
            nationality: 'أندوري',
            capital: 'أندورا لا فيلا',
          },
          {
            iso: 'AO',
            printableName: 'أنغولا',
            phonePrefix: '244',
            nationality: 'أنغولي',
            capital: 'لواندا',
          },
          {
            iso: 'AI',
            printableName: 'أنغويلا',
            phonePrefix: '264',
            nationality: 'أنغويلي',
            capital: 'ذا فالي',
          },
          {
            iso: 'AQ',
            printableName: 'أنتاركتيكا',
            phonePrefix: '672',
            nationality: '',
            capital: '',
          },
          {
            iso: 'AG',
            printableName: 'أنتيغوا وباربودا',
            phonePrefix: '268',
            nationality: 'أنتيغوي، باربودي',
            capital: "سانت جون'س",
          },
          {
            iso: 'AR',
            printableName: 'الأرجنتين',
            phonePrefix: '54',
            nationality: 'أرجنتيني',
            capital: 'بوينس آيرس',
          },
          {
            iso: 'AM',
            printableName: 'أرمينيا',
            phonePrefix: '374',
            nationality: 'أرميني',
            capital: 'يريفان',
          },
          {
            iso: 'AW',
            printableName: 'أروبا',
            phonePrefix: '297',
            nationality: 'أروبي',
            capital: 'أورنجستاد',
          },
          {
            iso: 'AC',
            printableName: 'جزيرة أسنسيون',
            phonePrefix: '247',
            nationality: '',
            capital: 'جورج تاون',
          },
          {
            iso: 'AU',
            printableName: 'أستراليا',
            phonePrefix: '61',
            nationality: 'أسترالي',
            capital: 'كانبرا',
          },
          {
            iso: 'AT',
            printableName: 'النمسا',
            phonePrefix: '43',
            nationality: 'نمساوي',
            capital: 'فيينا',
          },
          {
            iso: 'AZ',
            printableName: 'أذربيجان',
            phonePrefix: '994',
            nationality: 'أذربيجاني',
            capital: 'باكو',
          },
          {
            iso: 'BS',
            printableName: 'الباهاما',
            phonePrefix: '242',
            nationality: 'باهامي',
            capital: 'ناساو',
          },
          {
            iso: 'BH',
            printableName: 'البحرين',
            phonePrefix: '973',
            nationality: 'بحريني',
            capital: 'المنامة',
          },
          {
            iso: 'BD',
            printableName: 'بنغلاديش',
            phonePrefix: '880',
            nationality: 'بنغلاديشي',
            capital: 'دكا',
          },
          {
            iso: 'BB',
            printableName: 'بربادوس',
            phonePrefix: '246',
            nationality: 'بربادوسي',
            capital: 'بريدج تاون',
          },
          {
            iso: 'BY',
            printableName: 'بيلاروس',
            phonePrefix: '375',
            nationality: 'بيلاروسي',
            capital: 'مينسك',
          },
          {
            iso: 'BE',
            printableName: 'بلجيكا',
            phonePrefix: '32',
            nationality: 'بلجيكي',
            capital: 'بروكسل',
          },
          {
            iso: 'BZ',
            printableName: 'بليز',
            phonePrefix: '501',
            nationality: 'بليزي',
            capital: 'بلموبان',
          },
          {
            iso: 'BJ',
            printableName: 'بنين',
            phonePrefix: '229',
            nationality: 'بنيني',
            capital: 'بورتو نوفو',
          },
          {
            iso: 'BM',
            printableName: 'برمودا',
            phonePrefix: '441',
            nationality: 'برمودي',
            capital: 'هاميلتون',
          },
          {
            iso: 'BT',
            printableName: 'بوتان',
            phonePrefix: '975',
            nationality: 'بوتاني',
            capital: 'تيمفو',
          },
          {
            iso: 'BO',
            printableName: 'بوليفيا',
            phonePrefix: '591',
            nationality: 'بوليفي',
            capital: 'سوكري',
          },
          {
            iso: 'BQ',
            printableName: 'بونير، سينت أوستاتيوس وسابا',
            phonePrefix: '599',
            nationality: '',
            capital: 'كراليندايك',
          },
          {
            iso: 'BA',
            printableName: 'البوسنة والهرسك',
            phonePrefix: '387',
            nationality: 'بوسني، هرزي',
            capital: 'سراييفو',
          },
          {
            iso: 'BW',
            printableName: 'بوتسوانا',
            phonePrefix: '267',
            nationality: 'بوتسواني',
            capital: 'غابورون',
          },
          {
            iso: 'BV',
            printableName: 'جزيرة بوفيت',
            phonePrefix: '000',
            nationality: '',
            capital: '',
          },
          {
            iso: 'BR',
            printableName: 'البرازيل',
            phonePrefix: '55',
            nationality: 'برازيلي',
            capital: 'برازيليا',
          },
          {
            iso: 'IO',
            printableName: 'إقليم المحيط الهندي البريطاني',
            phonePrefix: '000',
            nationality: '',
            capital: 'دييغو غارسيا',
          },
          {
            iso: 'BN',
            printableName: 'بروناي دار السلام',
            phonePrefix: '673',
            nationality: 'بروناي',
            capital: 'بندر سري بكاوان',
          },
          {
            iso: 'BG',
            printableName: 'بلغاريا',
            phonePrefix: '359',
            nationality: 'بلغاري',
            capital: 'صوفيا',
          },
          {
            iso: 'BF',
            printableName: 'بوركينا فاسو',
            phonePrefix: '226',
            nationality: 'بوركيني',
            capital: 'واغادوغو',
          },
          {
            iso: 'BI',
            printableName: 'بوروندي',
            phonePrefix: '257',
            nationality: 'بوروندي',
            capital: 'جيتيغا',
          },
          {
            iso: 'KH',
            printableName: 'كمبوديا',
            phonePrefix: '855',
            nationality: 'كمبودي',
            capital: 'بنوم بنه',
          },
          {
            iso: 'CM',
            printableName: 'الكاميرون',
            phonePrefix: '237',
            nationality: 'كاميروني',
            capital: 'ياوندي',
          },
          {
            iso: 'CA',
            printableName: 'كندا',
            phonePrefix: '1',
            nationality: 'كندي',
            capital: 'أوتاوا',
          },
          {
            iso: 'IC',
            printableName: 'جزر الكناري',
            phonePrefix: '928',
            nationality: '',
            capital: 'سانتا كروز دي تينيريفي',
          },
          // {
          //   iso: 'SX',
          //   printableName: 'جزر الكناري',
          //   phonePrefix: '721',
          //   nationality: '',
          // },
          {
            iso: 'CV',
            printableName: 'الرأس الأخضر',
            phonePrefix: '238',
            nationality: 'الرأس الأخضري',
            capital: 'برايا',
          },
          {
            iso: 'KY',
            printableName: 'جزر كايمان',
            phonePrefix: '345',
            nationality: 'كايماني',
            capital: 'جورج تاون',
          },
          {
            iso: 'CF',
            printableName: 'جمهورية أفريقيا الوسطى',
            phonePrefix: '236',
            nationality: 'أفريقي وسطي',
            capital: 'بانغي',
          },
          {
            iso: 'EA',
            printableName: 'سبتة، مليلية',
            phonePrefix: '341',
            nationality: '',
            capital: 'سبتة',
          },
          {
            iso: 'TD',
            printableName: 'تشاد',
            phonePrefix: '235',
            nationality: 'تشادي',
            capital: "انجمينا",
          },
          {
            iso: 'CL',
            printableName: 'تشيلي',
            phonePrefix: '56',
            nationality: 'تشيلي',
            capital: 'سانتياغو',
          },
          {
            iso: 'CN',
            printableName: 'الصين',
            phonePrefix: '86',
            nationality: 'صيني',
            capital: 'بكين',
          },

          {
            iso: 'CX',
            printableName: 'جزيرة كريسماس',
            phonePrefix: '61',
            nationality: '',
            capital: 'فلاينغ فيش كوف',
          },
          {
            iso: 'CP',
            printableName: 'جزيرة كليبرتون',
            phonePrefix: '262',
            nationality: '',
            capital: '',
          },
          {
            iso: 'CC',
            printableName: 'جزر كوكوس (كيلينغ)',
            phonePrefix: '61',
            nationality: '',
            capital: 'ويست آيلاند',
          },
          {
            iso: 'CO',
            printableName: 'كولومبيا',
            phonePrefix: '57',
            nationality: 'كولومبي',
            capital: 'بوغوتا',
          },
          {
            iso: 'KM',
            printableName: 'جزر القمر',
            phonePrefix: '269',
            nationality: 'قمري',
            capital: 'موروني',
          },
          {
            iso: 'CG',
            printableName: 'الكونغو',
            phonePrefix: '242',
            nationality: 'كونغولي',
            capital: 'برازافيل',
          },
          {
            iso: 'CD',
            printableName: 'جمهورية الكونغو الديمقراطية',
            phonePrefix: '243',
            nationality: 'كونغولي',
            capital: 'كينشاسا',
          },
          {
            iso: 'CK',
            printableName: 'جزر كوك',
            phonePrefix: '682',
            nationality: 'كوكي',
            capital: 'أفاروا',
          },
          {
            iso: 'CR',
            printableName: 'كوستاريكا',
            phonePrefix: '506',
            nationality: 'كوستاريكي',
            capital: 'سان خوسيه',
          },
          {
            iso: 'CI',
            printableName: 'كوت ديفوار',
            phonePrefix: '225',
            nationality: 'إيفواري',
            capital: 'ياموسوكرو',
          },
          {
            iso: 'HR',
            printableName: 'كرواتيا',
            phonePrefix: '385',
            nationality: 'كرواتي',
            capital: 'زغرب',
          },
          {
            iso: 'CU',
            printableName: 'كوبا',
            phonePrefix: '53',
            nationality: 'كوبي',
            capital: 'هافانا',
          },
          {
            iso: 'CW',
            printableName: 'كوراساو',
            phonePrefix: '599',
            nationality: 'كوراساوي',
            capital: 'ويليمستاد',
          },
          {
            iso: 'CY',
            printableName: 'قبرص',
            phonePrefix: '357',
            nationality: 'قبرصي',
            capital: 'نيقوسيا',
          },
          {
            iso: 'CZ',
            printableName: 'جمهورية التشيك',
            phonePrefix: '420',
            nationality: 'تشيكي',
            capital: 'براغ',
          },
          {
            iso: 'DK',
            printableName: 'الدنمارك',
            phonePrefix: '45',
            nationality: 'دنماركي',
            capital: 'كوبنهاغن',
          },
          {
            iso: 'DG',
            printableName: 'دييغو غارسيا',
            phonePrefix: '246',
            nationality: '',
            capital: 'دييغو غارسيا',
          },
          {
            iso: 'DJ',
            printableName: 'جيبوتي',
            phonePrefix: '253',
            nationality: 'جيبوتي',
            capital: 'جيبوتي',
          },
          {
            iso: 'DM',
            printableName: 'دومينيكا',
            phonePrefix: '767',
            nationality: 'دومينيكي',
            capital: 'روزو',
          },
          {
            iso: 'DO',
            printableName: 'جمهورية الدومينيكان',
            phonePrefix: '809',
            nationality: 'دومينيكاني',
            capital: 'سانتو دومينغو',
          },
          {
            iso: 'EC',
            printableName: 'الإكوادور',
            phonePrefix: '593',
            nationality: 'إكوادوري',
            capital: 'كيتو',
          },
          {
            iso: 'EG',
            printableName: 'مصر',
            phonePrefix: '20',
            nationality: 'مصري',
            capital: 'القاهرة',
          },
          {
            iso: 'SV',
            printableName: 'السلفادور',
            phonePrefix: '503',
            nationality: 'سلفادوري',
            capital: 'سان سلفادور',
          },
          {
            iso: 'GQ',
            printableName: 'غينيا الاستوائية',
            phonePrefix: '240',
            nationality: 'غيني استوائي',
            capital: 'مالابو',
          },
          {
            iso: 'ER',
            printableName: 'إريتريا',
            phonePrefix: '291',
            nationality: 'إريتري',
            capital: 'أسمرة',
          },
          {
            iso: 'EE',
            printableName: 'إستونيا',
            phonePrefix: '372',
            nationality: 'إستوني',
            capital: 'تالين',
          },
          {
            iso: 'ET',
            printableName: 'إثيوبيا',
            phonePrefix: '251',
            nationality: 'إثيوبي',
            capital: 'أديس أبابا',
          },
          {
            iso: 'FK',
            printableName: 'جزر فوكلاند',
            phonePrefix: '500',
            nationality: 'فوكلاندي',
            capital: 'ستانلي',
          },
          {
            iso: 'FO',
            printableName: 'جزر فارو',
            phonePrefix: '298',
            nationality: 'فاروي',
            capital: 'تورشافن',
          },
          {
            iso: 'FJ',
            printableName: 'فيجي',
            phonePrefix: '679',
            nationality: 'فيجي',
            capital: 'سوفا',
          },
          {
            iso: 'FI',
            printableName: 'فنلندا',
            phonePrefix: '358',
            nationality: 'فنلندي',
            capital: 'هلسنكي',
          },
          {
            iso: 'FR',
            printableName: 'فرنسا',
            phonePrefix: '33',
            nationality: 'فرنسي',
            capital: 'باريس',
          },
          {
            iso: 'GF',
            printableName: 'غيانا الفرنسية',
            phonePrefix: '594',
            nationality: '',
            capital: 'كايين',
          },
          {
            iso: 'PF',
            printableName: 'بولينيزيا الفرنسية',
            phonePrefix: '689',
            nationality: '',
            capital: 'بابيتي',
          },
          {
            iso: 'TF',
            printableName: 'الأقاليم الجنوبية الفرنسية',
            phonePrefix: '000',
            nationality: '',
            capital: 'بورت أو فرانسيه',
          },
          {
            iso: 'GA',
            printableName: 'الغابون',
            phonePrefix: '241',
            nationality: 'غابوني',
            capital: 'ليبرفيل',
          },
          {
            iso: 'GM',
            printableName: 'غامبيا',
            phonePrefix: '220',
            nationality: 'غامبي',
            capital: 'بانجول',
          },
          {
            iso: 'GE',
            printableName: 'جورجيا',
            phonePrefix: '995',
            nationality: 'جورجي',
            capital: 'تبليسي',
          },
          {
            iso: 'DE',
            printableName: 'ألمانيا',
            phonePrefix: '49',
            nationality: 'ألماني',
            capital: 'برلين',
          },
          {
            iso: 'GH',
            printableName: 'غانا',
            phonePrefix: '233',
            nationality: 'غاني',
            capital: 'أكرا',
          },
          {
            iso: 'GI',
            printableName: 'جبل طارق',
            phonePrefix: '350',
            nationality: 'جبل طارق',
            capital: 'جبل طارق',
          },
          {
            iso: 'GR',
            printableName: 'اليونان',
            phonePrefix: '30',
            nationality: 'يوناني',
            capital: 'أثينا',
          },
          {
            iso: 'GL',
            printableName: 'غرينلاند',
            phonePrefix: '299',
            nationality: 'غرينلاندي',
            capital: 'نوك',
          },
          {
            iso: 'GD',
            printableName: 'غرينادا',
            phonePrefix: '473',
            nationality: 'غرينادي',
            capital: "سانت جورج'س",
          },
          {
            iso: 'GP',
            printableName: 'جوادلوب',
            phonePrefix: '590',
            nationality: '',
            capital: 'باس تير',
          },
          {
            iso: 'GU',
            printableName: 'غوام',
            phonePrefix: '671',
            nationality: 'غوامي',
            capital: 'هاغاتنيا',
          },
          {
            iso: 'GT',
            printableName: 'غواتيمالا',
            phonePrefix: '502',
            nationality: 'غواتيمالي',
            capital: 'غواتيمالا سيتي',
          },
          {
            iso: 'GG',
            printableName: 'غيرنزي',
            phonePrefix: '44',
            nationality: '',
            capital: 'سانت بيتر بورت',
          },
          {
            iso: 'GN',
            printableName: 'غينيا',
            phonePrefix: '224',
            nationality: 'غيني',
            capital: 'كوناكري',
          },
          {
            iso: 'GW',
            printableName: 'غينيا بيساو',
            phonePrefix: '245',
            nationality: 'غيني بيساوي',
            capital: 'بيساو',
          },
          {
            iso: 'GY',
            printableName: 'غيانا',
            phonePrefix: '592',

            nationality: 'غياني',
            capital: 'جورج تاون',
          },
          {
            iso: 'HT',
            printableName: 'هايتي',
            phonePrefix: '509',
            nationality: 'هايتي',
            capital: 'بورت أو برانس',
          },
          {
            iso: 'HM',
            printableName: 'جزيرة هيرد وجزر ماكدونالد',
            phonePrefix: '000',
            nationality: '',
            capital: '',
          },
          {
            iso: 'VA',
            printableName: 'الكرسي الرسولي (دولة الفاتيكان)',
            phonePrefix: '379',
            nationality: 'فاتيكان',
            capital: 'الفاتيكان',
          },
          {
            iso: 'HN',
            printableName: 'هندوراس',
            phonePrefix: '504',
            nationality: 'هندوراسي',
            capital: 'تيغوسيغالبا',
          },
          {
            iso: 'HK',
            printableName: 'هونغ كونغ',
            phonePrefix: '852',
            nationality: 'هونغ كونغي',
            capital: 'هونغ كونغ',
          },
          {
            iso: 'HU',
            printableName: 'المجر',
            phonePrefix: '36',
            nationality: 'مجري',
            capital: 'بودابست',
          },
          {
            iso: 'IS',
            printableName: 'آيسلندا',
            phonePrefix: '354',
            nationality: 'آيسلندي',
            capital: 'ريكيافيك',
          },
          {
            iso: 'IN',
            printableName: 'الهند',
            phonePrefix: '91',
            nationality: 'هندي',
            capital: 'نيودلهي',
          },
          {
            iso: 'ID',
            printableName: 'إندونيسيا',
            phonePrefix: '62',
            nationality: 'إندونيسي',
            capital: 'جاكرتا',
          },
          {
            iso: 'IR',
            printableName: 'إيران، جمهورية',
            phonePrefix: '98',
            nationality: 'إيراني',
            capital: 'طهران',
          },
          {
            iso: 'IQ',
            printableName: 'العراق',
            phonePrefix: '964',
            nationality: 'عراقي',
            capital: 'بغداد',
          },
          {
            iso: 'IE',
            printableName: 'أيرلندا',
            phonePrefix: '353',
            nationality: 'أيرلندي',
            capital: 'دبلن',
          },
          {
            iso: 'IM',
            printableName: 'جزيرة مان',
            phonePrefix: '44',
            nationality: 'مانكسي',
            capital: 'دوغلاس',
          },
          {
            iso: 'IL',
            printableName: 'إسرائيل',
            phonePrefix: '972',
            nationality: 'إسرائيلي',
            capital: 'القدس',
          },
          {
            iso: 'IT',
            printableName: 'إيطاليا',
            phonePrefix: '39',
            nationality: 'إيطالي',
            capital: 'روما',
          },
          {
            iso: 'JM',
            printableName: 'جامايكا',
            phonePrefix: '876',
            nationality: 'جامايكي',
            capital: 'كينغستون',
          },
          {
            iso: 'JP',
            printableName: 'اليابان',
            phonePrefix: '81',
            nationality: 'ياباني',
            capital: 'طوكيو',
          },
          {
            iso: 'JE',
            printableName: 'جيرسي',
            phonePrefix: '44',
            nationality: '',
            capital: 'سانت هيلير',
          },
          {
            iso: 'JO',
            printableName: 'الأردن',
            phonePrefix: '962',
            nationality: 'أردني',
            capital: 'عمان',
          },
          {
            iso: 'KZ',
            printableName: 'كازاخستان',
            phonePrefix: '7',
            nationality: 'كازاخستاني',
            capital: 'نور سلطان',
          },
          {
            iso: 'KE',
            printableName: 'كينيا',
            phonePrefix: '254',
            nationality: 'كيني',
            capital: 'نيروبي',
          },
          {
            iso: 'KI',
            printableName: 'كيريباتي',
            phonePrefix: '686',
            nationality: 'كيريباتي',
            capital: 'تاراوا',
          },
          {
            iso: 'KP',
            printableName: 'كوريا، جمهورية',
            phonePrefix: '850',
            nationality: 'كوري شمالي',
            capital: 'بيونغيانغ',
          },
          {
            iso: 'KR',
            printableName: 'كوريا الجنوبية',
            phonePrefix: '82',
            nationality: 'كوري جنوبي',
            capital: 'سيول',
          },
          {
            iso: 'KW',
            printableName: 'الكويت',
            phonePrefix: '965',
            nationality: 'كويتي',
            capital: 'الكويت',
          },
          {
            iso: 'KG',
            printableName: 'قيرغيزستان',
            phonePrefix: '996',
            nationality: 'قيرغيزي',
            capital: 'بيشكيك',
          },
          {
            iso: 'LA',
            printableName: 'لاوس',
            phonePrefix: '856',
            nationality: 'لاوسي',
            capital: 'فيينتيان',
          },
          {
            iso: 'LV',
            printableName: 'لاتفيا',
            phonePrefix: '371',
            nationality: 'لاتفي',
            capital: 'ريغا',
          },
          {
            iso: 'LB',
            printableName: 'لبنان',
            phonePrefix: '961',
            nationality: 'لبناني',
            capital: 'بيروت',
          },
          {
            iso: 'LS',
            printableName: 'ليسوتو',
            phonePrefix: '266',
            nationality: 'ليسوتو',
            capital: 'ماسيرو',
          },
          {
            iso: 'LR',
            printableName: 'ليبيريا',
            phonePrefix: '231',
            nationality: 'ليبيري',
            capital: 'مونروفيا',
          },
          {
            iso: 'LY',
            printableName: 'ليبيا',
            phonePrefix: '218',
            nationality: 'ليبي',
            capital: 'طرابلس',
          },
          {
            iso: 'LI',
            printableName: 'ليختنشتاين',
            phonePrefix: '423',
            nationality: 'ليختنشتايني',
            capital: 'فادوز',
          },
          {
            iso: 'LT',
            printableName: 'ليتوانيا',
            phonePrefix: '370',
            nationality: 'ليتواني',
            capital: 'فيلنيوس',
          },
          {
            iso: 'LU',
            printableName: 'لوكسمبورغ',
            phonePrefix: '352',
            nationality: 'لوكسمبورغي',
            capital: 'لوكسمبورغ',
          },
          {
            iso: 'MO',
            printableName: 'ماكاو',
            phonePrefix: '853',
            nationality: 'ماكاوي',
            capital: 'ماكاو',
          },
          {
            iso: 'MK',
            printableName: 'مقدونيا، الجمهورية اليوغوسلافية السابقة',
            phonePrefix: '389',
            nationality: 'مقدوني',
            capital: 'سكوبي',
          },
          {
            iso: 'MG',
            printableName: 'مدغشقر',
            phonePrefix: '261',
            nationality: 'مدغشقري',
            capital: 'أنتاناناريفو',
          },
          {
            iso: 'MW',
            printableName: 'ملاوي',
            phonePrefix: '265',
            nationality: 'ملاوي',
            capital: 'ليلونغوي',
          },
          {
            iso: 'MY',
            printableName: 'ماليزيا',
            phonePrefix: '60',
            nationality: 'ماليزي',
            capital: 'كوالالمبور',
          },
          {
            iso: 'MV',
            printableName: 'المالديف',
            phonePrefix: '960',
            nationality: 'مالديفي',
            capital: 'ماليه',
          },
          {
            iso: 'ML',
            printableName: 'مالي',
            phonePrefix: '223',
            nationality: 'مالي',
            capital: 'باماكو',
          },
          {
            iso: 'MT',
            printableName: 'مالطا',
            phonePrefix: '356',
            nationality: 'مالطي',
            capital: 'فاليتا',
          },
          {
            iso: 'MH',
            printableName: 'جزر مارشال',
            phonePrefix: '692',
            nationality: 'مارشالي',
            capital: 'ماجورو',
          },
          {
            iso: 'MQ',
            printableName: 'مارتينيك',
            phonePrefix: '596',
            nationality: '',
            capital: 'فور دو فرانس',
          },
          {
            iso: 'MR',
            printableName: 'موريتانيا',
            phonePrefix: '222',
            nationality: 'موريتاني',
            capital: 'نواكشوط',
          },
          {
            iso: 'MU',
            printableName: 'موريشيوس',
            phonePrefix: '230',
            nationality: 'موريشيوسي',
            capital: 'بورت لويس',
          },
          {
            iso: 'YT',
            printableName: 'مايوت',
            phonePrefix: '262',
            nationality: '',
            capital: 'مامودزو',
          },
          {
            iso: 'MX',
            printableName: 'المكسيك',
            phonePrefix: '52',
            nationality: 'مكسيكي',
            capital: 'مكسيكو سيتي',
          },
          {
            iso: 'FM',
            printableName: 'ولايات ميكرونيزيا المتحدة',
            phonePrefix: '691',
            nationality: 'ميكرونيزي',
            capital: 'باليكير',
          },
          {
            iso: 'MD',
            printableName: 'مولدوفا، جمهورية',
            phonePrefix: '373',
            nationality: 'مولدوفي',
            capital: 'كيشيناو',
          },
          {
            iso: 'MC',
            printableName: 'موناكو',
            phonePrefix: '377',
            nationality: 'موناكي',
            capital: 'موناكو',
          },
          {
            iso: 'MN',
            printableName: 'منغوليا',
            phonePrefix: '976',
            nationality: 'منغولي',
            capital: 'أولان باتور',
          },
          {
            iso: 'ME',
            printableName: 'الجبل الأسود',
            phonePrefix: '382',
            nationality: 'مونتينيغري',
            capital: 'بودغوريتسا',
          },
          {
            iso: 'MS',
            printableName: 'مونتسيرات',
            phonePrefix: '664',
            nationality: 'مونتسيراتي',
            capital: 'بليموث',
          },
          {
            iso: 'MA',
            printableName: 'المغرب',
            phonePrefix: '212',
            nationality: 'مغربي',
            capital: 'الرباط',
          },
          {
            iso: 'MZ',
            printableName: 'موزمبيق',
            phonePrefix: '258',
            nationality: 'موزمبيقي',
            capital: 'مابوتو',
          },
          {
            iso: 'MM',
            printableName: 'ميانمار',
            phonePrefix: '95',
            nationality: 'بورمي',
            capital: 'نايبيداو',
          },
          {
            iso: 'NA',
            printableName: 'ناميبيا',
            phonePrefix: '264',
            nationality: 'ناميبي',
            capital: 'ويندهوك',
          },
          {
            iso: 'NR',
            printableName: 'ناورو',
            phonePrefix: '674',
            nationality: 'ناوروي',
            capital: 'يارين',
          },
          {
            iso: 'NP',
            printableName: 'نيبال',
            phonePrefix: '977',
            nationality: 'نيبالي',
            capital: 'كاتماندو',
          },
          {
            iso: 'NL',
            printableName: 'هولندا',
            phonePrefix: '31',
            nationality: 'هولندي',
            capital: 'أمستردام',
          },
          {
            iso: 'NC',
            printableName: 'كاليدونيا الجديدة',
            phonePrefix: '687',
            nationality: 'كاليدوني جديد',
            capital: 'نوميا',
          },
          {
            iso: 'NZ',
            printableName: 'نيوزيلندا',
            phonePrefix: '64',
            nationality: 'نيوزيلندي',
            capital: 'ويلينغتون',
          },
          {
            iso: 'NI',
            printableName: 'نيكاراغوا',
            phonePrefix: '505',
            nationality: 'نيكاراغوي',
            capital: 'ماناغوا',
          },
          {
            iso: 'NE',
            printableName: 'النيجر',
            phonePrefix: '227',
            nationality: 'نيجيري',
            capital: 'نيامي',
          },
          {
            iso: 'NG',
            printableName: 'نيجيريا',
            phonePrefix: '234',
            nationality: 'نيجيري',
            capital: 'أبوجا',
          },
          {
            iso: 'NU',
            printableName: 'نيوي',
            phonePrefix: '683',
            nationality: 'نيوي',
            capital: 'ألوفي',
          },
          {
            iso: 'NF',
            printableName: 'جزيرة نورفولك',
            phonePrefix: '672',
            nationality: '',
            capital: 'كينغستون',
          },
          {
            iso: 'MP',
            printableName: 'جزر ماريانا الشمالية',
            phonePrefix: '670',
            nationality: 'مارياني شمالي',
            capital: 'سايبان',
          },
          {
            iso: 'NO',
            printableName: 'النرويج',
            phonePrefix: '47',
            nationality: 'نرويجي',
            capital: 'أوسلو',
          },
          {
            iso: 'OM',
            printableName: 'عمان',
            phonePrefix: '968',
            nationality: 'عماني',
            capital: 'مسقط',
          },
          {
            iso: 'PK',
            printableName: 'باكستان',
            phonePrefix: '92',
            nationality: 'باكستاني',
            capital: 'إسلام آباد',
          },
          {
            iso: 'PW',
            printableName: 'بالاو',
            phonePrefix: '680',
            nationality: 'بالاوي',
            capital: 'نجرولمود',
          },
          {
            iso: 'PS',
            printableName: 'الأراضي الفلسطينية المحتلة',
            phonePrefix: '970',
            nationality: 'فلسطيني',
            capital: 'القدس الشرقية',
          },
          {
            iso: 'PA',
            printableName: 'بنما',
            phonePrefix: '507',
            nationality: 'بنمي',
            capital: 'بنما سيتي',
          },
          {
            iso: 'PG',
            printableName: 'بابوا غينيا الجديدة',
            phonePrefix: '675',
            nationality: 'بابوا غيني جديد',
            capital: 'بورت مورسبي',
          },
          {
            iso: 'PY',
            printableName: 'باراغواي',
            phonePrefix: '595',
            nationality: 'باراغواياني',
            capital: 'أسونسيون',
          },
          {
            iso: 'PE',
            printableName: 'بيرو',
            phonePrefix: '51',
            nationality: 'بيري',
            capital: 'ليما',
          },
          {
            iso: 'PH',
            printableName: 'الفلبين',
            phonePrefix: '63',
            nationality: 'فلبيني',
            capital: 'مانيلا',
          },
          {
            iso: 'PN',
            printableName: 'بيتكيرن',
            phonePrefix: '870',
            nationality: '',
            capital: 'آدمزتاون',
          },
          {
            iso: 'PL',
            printableName: 'بولندا',
            phonePrefix: '48',
            nationality: 'بولندي',
            capital: 'وارسو',
          },
          {
            iso: 'PT',
            printableName: 'البرتغال',
            phonePrefix: '351',
            nationality: 'برتغالي',
            capital: 'لشبونة',
          },
          {
            iso: 'PR',
            printableName: 'بورتوريكو',
            phonePrefix: '1',
            nationality: 'بورتوريكي',
            capital: 'سان خوان',
          },
          {
            iso: 'QA',
            printableName: 'قطر',
            phonePrefix: '974',
            nationality: 'قطري',
            capital: 'الدوحة',
          },
          {
            iso: 'RE',
            printableName: 'ريونيون',
            phonePrefix: '262',
            nationality: '',
            capital: 'سانت دينيس',
          },
          {
            iso: 'RO',
            printableName: 'رومانيا',
            phonePrefix: '40',
            nationality: 'روماني',
            capital: 'بوخارست',
          },
          {
            iso: 'RU',
            printableName: 'روسيا الاتحادية',
            phonePrefix: '7',
            nationality: 'روسي',
            capital: 'موسكو',
          },
          {
            iso: 'RW',
            printableName: 'رواندا',
            phonePrefix: '250',
            nationality: 'رواندي',
            capital: 'كيغالي',
          },
          {
            iso: 'BL',
            printableName: 'سان بارتيلمي',
            phonePrefix: '590',
            nationality: '',
            capital: 'غوستافيا',
          },
          {
            iso: 'SH',
            printableName: 'سانت هيلينا، أسينسيون وتريستان دا كونها',
            phonePrefix: '290',
            nationality: '',
            capital: 'جيمستاون',
          },
          {
            iso: 'KN',
            printableName: 'سانت كيتس ونيفيس',
            phonePrefix: '1',
            nationality: 'كيتسي، نيفيسي',
            capital: 'باسيتير',
          },
          {
            iso: 'LC',
            printableName: 'سانت لوسيا',
            phonePrefix: '1',
            nationality: 'لوسياني',
            capital: 'كاستريس',
          },
          {
            iso: 'MF',
            printableName: 'سانت مارتن (الجزء الفرنسي)',
            phonePrefix: '590',
            nationality: '',
            capital: 'ماريغوت',
          },
          {
            iso: 'PM',
            printableName: 'سان بيير وميكلون',
            phonePrefix: '508',
            nationality: '',
            capital: 'سان بيير',
          },
          {
            iso: 'VC',
            printableName: 'سانت فنسنت وجزر غرينادين',
            phonePrefix: '1',
            nationality: 'فنسنتي',
            capital: 'كينغستاون',
          },
          {
            iso: 'WS',
            printableName: 'ساموا',
            phonePrefix: '685',
            nationality: 'ساموي',
            capital: 'أبيا',
          },
          {
            iso: 'SM',
            printableName: 'سان مارينو',
            phonePrefix: '378',
            nationality: 'ماريني',
            capital: 'سان مارينو',
          },
          {
            iso: 'ST',
            printableName: 'ساو تومي وبرينسيبي',
            phonePrefix: '239',
            nationality: 'ساو تومي وبرينسيبي',
            capital: 'ساو تومي',
          },
          {
            iso: 'SA',
            printableName: 'المملكة العربية السعودية',
            phonePrefix: '966',
            nationality: 'سعودي',
            capital: 'الرياض',
          },
          {
            iso: 'SN',
            printableName: 'السنغال',
            phonePrefix: '221',
            nationality: 'سنغالي',
            capital: 'داكار',
          },
          {
            iso: 'RS',
            printableName: 'صربيا',
            phonePrefix: '381',
            nationality: 'صربي',
            capital: 'بلغراد',
          },
          {
            iso: 'SC',
            printableName: 'سيشيل',
            phonePrefix: '248',
            nationality: 'سيشلي',
            capital: 'فيكتوريا',
          },
          {
            iso: 'SL',
            printableName: 'سيراليون',
            phonePrefix: '232',
            nationality: 'سيراليوني',
            capital: 'فريتاون',
          },
          {
            iso: 'SG',
            printableName: 'سنغافورة',
            phonePrefix: '65',
            nationality: 'سنغافوري',
            capital: 'سنغافورة',
          },
          {
            iso: 'SX',
            printableName: 'سينت مارتن (الجزء الهولندي)',
            phonePrefix: '1',
            nationality: '',
            capital: 'فيليبسبورغ',
          },
          {
            iso: 'SK',
            printableName: 'سلوفاكيا',
            phonePrefix: '421',
            nationality: 'سلوفاكي',
            capital: 'براتيسلافا',
          },
          {
            iso: 'SI',
            printableName: 'سلوفينيا',
            phonePrefix: '386',
            nationality: 'سلوفيني',
            capital: 'ليوبليانا',
          },
          {
            iso: 'SB',
            printableName: 'جزر سليمان',
            phonePrefix: '677',
            nationality: 'سليماني',
            capital: 'هونيارا',
          },
          {
            iso: 'SO',
            printableName: 'الصومال',
            phonePrefix: '252',
            nationality: 'صومالي',
            capital: 'مقديشو',
          },
          {
            iso: 'ZA',
            printableName: 'جنوب أفريقيا',
            phonePrefix: '27',
            nationality: 'جنوب أفريقي',
            capital: 'كيب تاون',
          },
          {
            iso: 'GS',
            printableName: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
            phonePrefix: '500',
            nationality: '',
            capital: 'كينغ إدوارد بوينت',
          },
          {
            iso: 'SS',
            printableName: 'جنوب السودان',
            phonePrefix: '211',
            nationality: 'جنوب سوداني',
            capital: 'جوبا',
          },
          {
            iso: 'ES',
            printableName: 'إسبانيا',
            phonePrefix: '34',
            nationality: 'إسباني',
            capital: 'مدريد',
          },
          {
            iso: 'LK',
            printableName: 'سريلانكا',
            phonePrefix: '94',
            nationality: 'سريلانكي',
            capital: 'كولومبو',
          },
          {
            iso: 'SD',
            printableName: 'السودان',
            phonePrefix: '249',
            nationality: 'سوداني',
            capital: 'الخرطوم',
          },
          {
            iso: 'SR',
            printableName: 'سورينام',
            phonePrefix: '597',
            nationality: 'سورينامي',
            capital: 'باراماريبو',
          },
          {
            iso: 'SJ',
            printableName: 'سفالبارد ويان ماين',
            phonePrefix: '47',
            nationality: '',
            capital: 'لونغيربين',
          },
          {
            iso: 'SZ',
            printableName: 'إسواتيني',
            phonePrefix: '268',
            nationality: 'سواتيني',
            capital: 'مبابان',
          },
          {
            iso: 'SE',
            printableName: 'السويد',
            phonePrefix: '46',
            nationality: 'سويدي',
            capital: 'ستوكهولم',
          },
          {
            iso: 'CH',
            printableName: 'سويسرا',
            phonePrefix: '41',
            nationality: 'سويسري',
            capital: 'برن',
          },
          {
            iso: 'SY',
            printableName: 'الجمهورية العربية السورية',
            phonePrefix: '963',
            nationality: 'سوري',
            capital: 'دمشق',
          },
          {
            iso: 'TW',
            printableName: 'تايوان، مقاطعة الصين',
            phonePrefix: '886',
            nationality: 'تايواني',
            capital: 'تايبي',
          },
          {
            iso: 'TJ',
            printableName: 'طاجيكستان',
            phonePrefix: '992',
            nationality: 'طاجيكستاني',
            capital: 'دوشانبي',
          },
          {
            iso: 'TZ',
            printableName: 'جمهورية تنزانيا المتحدة',
            phonePrefix: '255',
            nationality: 'تنزاني',
            capital: 'دودوما',
          },
          {
            iso: 'TH',
            printableName: 'تايلاند',
            phonePrefix: '66',
            nationality: 'تايلاندي',
            capital: 'بانكوك',
          },
          {
            iso: 'TL',
            printableName: 'تيمور الشرقية',
            phonePrefix: '670',
            nationality: 'تيموري',
            capital: 'ديلي',
          },
          {
            iso: 'TG',
            printableName: 'توغو',
            phonePrefix: '228',
            nationality: 'توغولي',
            capital: 'لومي',
          },
          {
            iso: 'TK',
            printableName: 'توكيلاو',
            phonePrefix: '690',
            nationality: '',
            capital: 'فاكاوفو',
          },
          {
            iso: 'TO',
            printableName: 'تونغا',
            phonePrefix: '676',
            nationality: 'تونغي',
            capital: 'نوكوالوفا',
          },
          {
            iso: 'TT',
            printableName: 'ترينيداد وتوباغو',
            phonePrefix: '1',
            nationality: 'ترينيدادي، توباغوني',
            capital: 'بورت أوف سبين',
          },
          {
            iso: 'TN',
            printableName: 'تونس',
            phonePrefix: '216',
            nationality: 'تونسي',
            capital: 'تونس',
          },
          {
            iso: 'TR',
            printableName: 'تركيا',
            phonePrefix: '90',
            nationality: 'تركي',
            capital: 'أنقرة',
          },
          {
            iso: 'TM',
            printableName: 'تركمانستان',
            phonePrefix: '993',
            nationality: 'تركماني',
            capital: 'عشق آباد',
          },
          {
            iso: 'TC',
            printableName: 'جزر توركس وكايكوس',
            phonePrefix: '1',
            nationality: '',
            capital: 'كوكبيرن تاون',
          },
          {
            iso: 'TV',
            printableName: 'توفالو',
            phonePrefix: '688',
            nationality: 'توفالي',
            capital: 'فونافوتي',
          },
          {
            iso: 'UG',
            printableName: 'أوغندا',
            phonePrefix: '256',
            nationality: 'أوغندي',
            capital: 'كامبالا',
          },
          {
            iso: 'UA',
            printableName: 'أوكرانيا',
            phonePrefix: '380',
            nationality: 'أوكراني',
            capital: 'كييف',
          },
          {
            iso: 'AE',
            printableName: 'الإمارات العربية المتحدة',
            phonePrefix: '971',
            nationality: 'إماراتي',
            capital: 'أبوظبي',
          },
          {
            iso: 'GB',
            printableName: 'المملكة المتحدة',
            phonePrefix: '44',
            nationality: 'بريطاني',
            capital: 'لندن',
          },
          {
            iso: 'US',
            printableName: 'الولايات المتحدة الأمريكية',
            phonePrefix: '1',
            nationality: 'أمريكي',
            capital: 'واشنطن',
          },
          {
            iso: 'UY',
            printableName: 'أوروغواي',
            phonePrefix: '598',
            nationality: 'أوروغواياني',
            capital: 'مونتيفيديو',
          },
          {
            iso: 'UZ',
            printableName: 'أوزبكستان',
            phonePrefix: '998',
            nationality: 'أوزبكي',
            capital: 'طشقند',
          },
          {
            iso: 'VU',
            printableName: 'فانواتو',
            phonePrefix: '678',
            nationality: 'فانواتي',
            capital: 'بورت فيلا',
          },
          {
            iso: 'VE',
            printableName: 'فنزويلا، جمهورية',
            phonePrefix: '58',
            nationality: 'فنزويلي',
            capital: 'كاراكاس',
          },
          {
            iso: 'VN',
            printableName: 'فيتنام',
            phonePrefix: '84',
            nationality: 'فيتنامي',
            capital: 'هانوي',
          },
          {
            iso: 'VG',
            printableName: 'جزر العذراء البريطانية',
            phonePrefix: '1',
            nationality: 'بريطاني فيرجيني',
            capital: 'رود تاون',
          },
          {
            iso: 'VI',
            printableName: 'جزر العذراء الأمريكية',
            phonePrefix: '1',
            nationality: 'أمريكي فيرجيني',
            capital: 'شارلوت أمالي',
          },
          {
            iso: 'WF',
            printableName: 'واليس وفوتونا',
            phonePrefix: '681',
            nationality: '',
            capital: 'ماتا أوتو',
          },
          {
            iso: 'EH',

            printableName: 'الصحراء الغربية',
            phonePrefix: '212',
            nationality: 'صحراوي',
            capital: 'العيون',
          },
          {
            iso: 'YE',
            printableName: 'اليمن',
            phonePrefix: '967',
            nationality: 'يمني',
            capital: 'صنعاء',
          },
          {
            iso: 'ZM',
            printableName: 'زامبيا',
            phonePrefix: '260',
            nationality: 'زامبي',
            capital: 'لوساكا',
          },
          {
            iso: 'ZW',
            printableName: 'زيمبابوي',
            phonePrefix: '263',
            nationality: 'زيمبابوي',
            capital: 'هراري',
          },
        ],
      };
    }
    return {
      result: [
        {
          iso: 'AF',
          printableName: 'Afghanistan',
          phonePrefix: '93',
          nationality: 'Afghan',
          capital: 'Kabul',
        },
        {
          iso: 'AX',
          printableName: 'Aland Islands',
          phonePrefix: '358',
          nationality: 'Alandic',
          capital: 'Mariehamn',
        },
        {
          iso: 'AL',
          printableName: 'Albania',
          phonePrefix: '355',
          nationality: 'Albanian',
          capital: 'Tirana',
        },
        {
          iso: 'DZ',
          printableName: 'Algeria',
          phonePrefix: '213',
          nationality: 'Algerian',
          capital: 'Algiers',
        },
        {
          iso: 'AS',
          printableName: 'American Samoa',
          phonePrefix: '684',
          nationality: 'American Samoan',
          capital: 'Pago Pago',
        },
        {
          iso: 'AD',
          printableName: 'Andorra',
          phonePrefix: '376',
          nationality: 'Andorran',
          capital: 'Andorra la Vella',
        },
        {
          iso: 'AO',
          printableName: 'Angola',
          phonePrefix: '244',
          nationality: 'Angolan',
          capital: 'Luanda',
        },
        {
          iso: 'AI',
          printableName: 'Anguilla',
          phonePrefix: '264',
          nationality: 'Anguillan',
          capital: 'The Valley',
        },
        {
          iso: 'AQ',
          printableName: 'Antarctica',
          phonePrefix: '672',
          nationality: '',
          capital: '',
        },
        {
          iso: 'AG',
          printableName: 'Antigua and Barbuda',
          phonePrefix: '268',
          nationality: 'Antiguan, Barbudan',
          capital: "Saint John's",
        },
        {
          iso: 'AR',
          printableName: 'Argentina',
          phonePrefix: '54',
          nationality: 'Argentinian',
          capital: 'Buenos Aires',
        },
        {
          iso: 'AM',
          printableName: 'Armenia',
          phonePrefix: '374',
          nationality: 'Armenian',
          capital: 'Yerevan',
        },
        {
          iso: 'AW',
          printableName: 'Aruba',
          phonePrefix: '297',
          nationality: 'Aruban',
          capital: 'Oranjestad',
        },
        {
          iso: 'AC',
          printableName: 'Ascension Island',
          phonePrefix: '247',
          nationality: '',
          capital: 'Georgetown',
        },
        {
          iso: 'AU',
          printableName: 'Australia',
          phonePrefix: '61',
          nationality: 'Australian',
          capital: 'Canberra',
        },
        {
          iso: 'AT',
          printableName: 'Austria',
          phonePrefix: '43',
          nationality: 'Austrian',
          capital: 'Vienna',
        },
        {
          iso: 'AZ',
          printableName: 'Azerbaijan',
          phonePrefix: '994',
          nationality: 'Azerbaijani',
          capital: 'Baku',
        },
        {
          iso: 'BS',
          printableName: 'Bahamas',
          phonePrefix: '242',
          nationality: 'Bahamian',
          capital: 'Nassau',
        },
        {
          iso: 'BH',
          printableName: 'Bahrain',
          phonePrefix: '973',
          nationality: 'Bahraini',
          capital: 'Manama',
        },
        {
          iso: 'BD',
          printableName: 'Bangladesh',
          phonePrefix: '880',
          nationality: 'Bangladeshi',
          capital: 'Dhaka',
        },
        {
          iso: 'BB',
          printableName: 'Barbados',
          phonePrefix: '246',
          nationality: 'Barbadian',
          capital: 'Bridgetown',
        },
        {
          iso: 'BY',
          printableName: 'Belarus',
          phonePrefix: '375',
          nationality: 'Belarusian',
          capital: 'Minsk',
        },
        {
          iso: 'BE',
          printableName: 'Belgium',
          phonePrefix: '32',
          nationality: 'Belgian',
          capital: 'Brussels',
        },
        {
          iso: 'BZ',
          printableName: 'Belize',
          phonePrefix: '501',
          nationality: 'Belizean',
          capital: 'Belmopan',
        },
        {
          iso: 'BJ',
          printableName: 'Benin',
          phonePrefix: '229',
          nationality: 'Beninese',
          capital: 'Porto-Novo',
        },
        {
          iso: 'BM',
          printableName: 'Bermuda',
          phonePrefix: '441',
          nationality: 'Bermudian',
          capital: 'Hamilton',
        },
        {
          iso: 'BT',
          printableName: 'Bhutan',
          phonePrefix: '975',
          nationality: 'Bhutanese',
          capital: 'Thimphu',
        },
        {
          iso: 'BO',
          printableName: 'Bolivia',
          phonePrefix: '591',
          nationality: 'Bolivian',
          capital: 'Sucre',
        },
        {
          iso: 'BQ',
          printableName: 'Bonaire, Sint Eustatius and Saba',
          phonePrefix: '599',
          nationality: '',
          capital: 'Kralendijk',
        },
        {
          iso: 'BA',
          printableName: 'Bosnia and Herzegovina',
          phonePrefix: '387',
          nationality: 'Bosnian, Herzegovinian',
          capital: 'Sarajevo',
        },
        {
          iso: 'BW',
          printableName: 'Botswana',
          phonePrefix: '267',
          nationality: 'Motswana',
          capital: 'Gaborone',
        },
        {
          iso: 'BV',
          printableName: 'Bouvet Island',
          phonePrefix: '000',
          nationality: '',
          capital: '',
        },
        {
          iso: 'BR',
          printableName: 'Brazil',
          phonePrefix: '55',
          nationality: 'Brazilian',
          capital: 'Brasília',
        },
        {
          iso: 'IO',
          printableName: 'British Indian Ocean Territory',
          phonePrefix: '000',
          nationality: '',
          capital: 'Diego Garcia',
        },
        {
          iso: 'BN',
          printableName: 'Brunei Darussalam',
          phonePrefix: '673',
          nationality: 'Bruneian',
          capital: 'Bandar Seri Begawan',
        },
        {
          iso: 'BG',
          printableName: 'Bulgaria',
          phonePrefix: '359',
          nationality: 'Bulgarian',
          capital: 'Sofia',
        },
        {
          iso: 'BF',
          printableName: 'Burkina Faso',
          phonePrefix: '226',
          nationality: 'Burkinabe',
          capital: 'Ouagadougou',
        },
        {
          iso: 'BI',
          printableName: 'Burundi',
          phonePrefix: '257',
          nationality: 'Burundian',
          capital: 'Gitega',
        },
        {
          iso: 'KH',
          printableName: 'Cambodia',
          phonePrefix: '855',
          nationality: 'Cambodian',
          capital: 'Phnom Penh',
        },
        {
          iso: 'CM',
          printableName: 'Cameroon',
          phonePrefix: '237',
          nationality: 'Cameroonian',
          capital: 'Yaoundé',
        },
        {
          iso: 'CA',
          printableName: 'Canada',
          phonePrefix: '1',
          nationality: 'Canadian',
          capital: 'Ottawa',
        },
        {
          iso: 'IC',
          printableName: 'Canary Islands',
          phonePrefix: '928',
          nationality: '',
          capital: 'Santa Cruz de Tenerife',
        },
        // {
        //   iso: 'SX',
        //   printableName: 'Canary Islands',
        //   phonePrefix: '721',
        //   nationality: '',
        // },
        {
          iso: 'CV',
          printableName: 'Cape Verde',
          phonePrefix: '238',
          nationality: 'Cape Verdean',
          capital: 'Praia',
        },
        {
          iso: 'KY',
          printableName: 'Cayman Islands',
          phonePrefix: '345',
          nationality: 'Caymanian',
          capital: 'George Town',
        },
        {
          iso: 'CF',
          printableName: 'Central African Republic',
          phonePrefix: '236',
          nationality: 'Central African',
          capital: 'Bangui',
        },
        {
          iso: 'EA',
          printableName: 'Ceuta, Melilla',
          phonePrefix: '341',
          nationality: '',
          capital: 'Ceuta',
        },
        {
          iso: 'TD',
          printableName: 'Chad',
          phonePrefix: '235',
          nationality: 'Chadian',
          capital: "N'Djamena",
        },
        {
          iso: 'CL',
          printableName: 'Chile',
          phonePrefix: '56',
          nationality: 'Chilean',
          capital: 'Santiago',
        },
        {
          iso: 'CN',
          printableName: 'China',
          phonePrefix: '86',
          nationality: 'Chinese',
          capital: 'Beijing',
        },
        {
          iso: 'CX',
          printableName: 'Christmas Island',
          phonePrefix: '61',
          nationality: '',
          capital: 'Flying Fish Cove',
        },
        {
          iso: 'CP',
          printableName: 'Clipperton Island',
          phonePrefix: '262',
          nationality: '',
          capital: '',
        },
        {
          iso: 'CC',
          printableName: 'Cocos (Keeling) Islands',
          phonePrefix: '61',
          nationality: '',
          capital: 'West Island',
        },
        {
          iso: 'CO',
          printableName: 'Colombia',
          phonePrefix: '57',
          nationality: 'Colombian',
          capital: 'Bogotá',
        },
        {
          iso: 'KM',
          printableName: 'Comoros',
          phonePrefix: '269',
          nationality: 'Comoran',
          capital: 'Moroni',
        },
        {
          iso: 'CG',
          printableName: 'Congo',
          phonePrefix: '242',
          nationality: 'Congolese',
          capital: 'Brazzaville',
        },
        {
          iso: 'CD',
          printableName: 'Congo, Democratic Republic of the',
          phonePrefix: '243',
          nationality: 'Congolese',
          capital: 'Kinshasa',
        },
        {
          iso: 'CK',
          printableName: 'Cook Islands',
          phonePrefix: '682',
          nationality: 'Cook Islander',
          capital: 'Avarua',
        },
        {
          iso: 'CR',
          printableName: 'Costa Rica',
          phonePrefix: '506',
          nationality: 'Costa Rican',
          capital: 'San José',
        },
        {
          iso: 'CI',
          printableName: "Cote d'Ivoire",
          phonePrefix: '225',
          nationality: 'Ivorian',
          capital: 'Yamoussoukro',
        },
        {
          iso: 'HR',
          printableName: 'Croatia',
          phonePrefix: '385',
          nationality: 'Croatian',
          capital: 'Zagreb',
        },
        {
          iso: 'CU',
          printableName: 'Cuba',
          phonePrefix: '53',
          nationality: 'Cuban',
          capital: 'Havana',
        },
        {
          iso: 'CW',
          printableName: 'Curacao',
          phonePrefix: '599',
          nationality: 'Curacaoan',
          capital: 'Willemstad',
        },
        {
          iso: 'CY',
          printableName: 'Cyprus',
          phonePrefix: '357',
          nationality: 'Cypriot',
          capital: 'Nicosia',
        },
        {
          iso: 'CZ',
          printableName: 'Czech Republic',
          phonePrefix: '420',
          nationality: 'Czech',
          capital: 'Prague',
        },
        {
          iso: 'DK',
          printableName: 'Denmark',
          phonePrefix: '45',
          nationality: 'Danish',
          capital: 'Copenhagen',
        },
        {
          iso: 'DG',
          printableName: 'Diego Garcia',
          phonePrefix: '246',
          nationality: '',
          capital: 'Diego Garcia',
        },
        {
          iso: 'DJ',
          printableName: 'Djibouti',
          phonePrefix: '253',
          nationality: 'Djiboutian',
          capital: 'Djibouti',
        },
        {
          iso: 'DM',
          printableName: 'Dominica',
          phonePrefix: '767',
          nationality: 'Dominican',
          capital: 'Roseau',
        },
        {
          iso: 'DO',
          printableName: 'Dominican Republic',
          phonePrefix: '809',
          nationality: 'Dominican',
          capital: 'Santo Domingo',
        },
        {
          iso: 'EC',
          printableName: 'Ecuador',
          phonePrefix: '593',
          nationality: 'Ecuadorian',
          capital: 'Quito',
        },
        {
          iso: 'EG',
          printableName: 'Egypt',
          phonePrefix: '20',
          nationality: 'Egyptian',
          capital: 'Cairo',
        },
        {
          iso: 'SV',
          printableName: 'El Salvador',
          phonePrefix: '503',
          nationality: 'Salvadoran',
          capital: 'San Salvador',
        },
        {
          iso: 'GQ',
          printableName: 'Equatorial Guinea',
          phonePrefix: '240',
          nationality: 'Equatorial Guinean',
          capital: 'Malabo',
        },
        {
          iso: 'ER',
          printableName: 'Eritrea',
          phonePrefix: '291',
          nationality: 'Eritrean',
          capital: 'Asmara',
        },
        {
          iso: 'EE',
          printableName: 'Estonia',
          phonePrefix: '372',
          nationality: 'Estonian',
          capital: 'Tallinn',
        },
        {
          iso: 'ET',
          printableName: 'Ethiopia',
          phonePrefix: '251',
          nationality: 'Ethiopian',
          capital: 'Addis Ababa',
        },
        {
          iso: 'FK',
          printableName: 'Falkland Islands (Malvinas)',
          phonePrefix: '500',
          nationality: 'Falkland Islander',
          capital: 'Stanley',
        },
        {
          iso: 'FO',
          printableName: 'Faroe Islands',
          phonePrefix: '298',
          nationality: 'Faroese',
          capital: 'Tórshavn',
        },
        {
          iso: 'FJ',
          printableName: 'Fiji',
          phonePrefix: '679',
          nationality: 'Fijian',
          capital: 'Suva',
        },
        {
          iso: 'FI',
          printableName: 'Finland',
          phonePrefix: '358',
          nationality: 'Finnish',
          capital: 'Helsinki',
        },
        {
          iso: 'FR',
          printableName: 'France',
          phonePrefix: '33',
          nationality: 'French',
          capital: 'Paris',
        },
        {
          iso: 'GF',
          printableName: 'French Guiana',
          phonePrefix: '594',
          nationality: '',
          capital: 'Cayenne',
        },
        {
          iso: 'PF',
          printableName: 'French Polynesia',
          phonePrefix: '689',
          nationality: '',
          capital: 'Papeete',
        },
        {
          iso: 'TF',
          printableName: 'French Southern Territories',
          phonePrefix: '000',
          nationality: '',
          capital: 'Port-aux-Français',
        },
        {
          iso: 'GA',
          printableName: 'Gabon',
          phonePrefix: '241',
          nationality: 'Gabonese',
          capital: 'Libreville',
        },
        {
          iso: 'GM',
          printableName: 'Gambia',
          phonePrefix: '220',
          nationality: 'Gambian',
          capital: 'Banjul',
        },
        {
          iso: 'GE',
          printableName: 'Georgia',
          phonePrefix: '995',
          nationality: 'Georgian',
          capital: 'Tbilisi',
        },
        {
          iso: 'DE',
          printableName: 'Germany',
          phonePrefix: '49',
          nationality: 'German',
          capital: 'Berlin',
        },
        {
          iso: 'GH',
          printableName: 'Ghana',
          phonePrefix: '233',
          nationality: 'Ghanaian',
          capital: 'Accra',
        },
        {
          iso: 'GI',
          printableName: 'Gibraltar',
          phonePrefix: '350',
          nationality: 'Gibraltar',
          capital: 'Gibraltar',
        },
        {
          iso: 'GR',
          printableName: 'Greece',
          phonePrefix: '30',
          nationality: 'Greek',
          capital: 'Athens',
        },
        {
          iso: 'GL',
          printableName: 'Greenland',
          phonePrefix: '299',
          nationality: 'Greenlandic',
          capital: 'Nuuk',
        },
        {
          iso: 'GD',
          printableName: 'Grenada',
          phonePrefix: '473',
          nationality: 'Grenadian',
          capital: "Saint George's",
        },
        {
          iso: 'GP',
          printableName: 'Guadeloupe',
          phonePrefix: '590',
          nationality: '',
          capital: 'Basse-Terre',
        },
        {
          iso: 'GU',
          printableName: 'Guam',
          phonePrefix: '671',
          nationality: 'Guamanian',
          capital: 'Hagåtña',
        },
        {
          iso: 'GT',
          printableName: 'Guatemala',
          phonePrefix: '502',
          nationality: 'Guatemalan',
          capital: 'Guatemala City',
        },
        {
          iso: 'GG',
          printableName: 'Guernsey',
          phonePrefix: '44',
          nationality: '',
          capital: 'Saint Peter Port',
        },
        {
          iso: 'GN',
          printableName: 'Guinea',
          phonePrefix: '224',
          nationality: 'Guinean',
          capital: 'Conakry',
        },
        {
          iso: 'GW',
          printableName: 'Guinea-Bissau',
          phonePrefix: '245',
          nationality: 'Guinean-Bissau',
          capital: 'Bissau',
        },
        {
          iso: 'GY',
          printableName: 'Guyana',
          phonePrefix: '592',
          nationality: 'Guyanese',
          capital: 'Georgetown',
        },
        {
          iso: 'HT',
          printableName: 'Haiti',
          phonePrefix: '509',
          nationality: 'Haitian',
          capital: 'Port-au-Prince',
        },
        {
          iso: 'HM',
          printableName: 'Heard Island and McDonald Islands',
          phonePrefix: '000',
          nationality: '',
          capital: '',
        },
        {
          iso: 'VA',
          printableName: 'Holy See (Vatican City State)',
          phonePrefix: '379',
          nationality: 'Vatican',
          capital: 'Vatican City',
        },
        {
          iso: 'HN',
          printableName: 'Honduras',
          phonePrefix: '504',
          nationality: 'Honduran',
          capital: 'Tegucigalpa',
        },
        {
          iso: 'HK',
          printableName: 'Hong Kong',
          phonePrefix: '852',
          nationality: 'Hong Konger',
          capital: 'Hong Kong',
        },
        {
          iso: 'HU',
          printableName: 'Hungary',
          phonePrefix: '36',
          nationality: 'Hungarian',
          capital: 'Budapest',
        },
        {
          iso: 'IS',
          printableName: 'Iceland',
          phonePrefix: '354',
          nationality: 'Icelander',
          capital: 'Reykjavik',
        },
        {
          iso: 'IN',
          printableName: 'India',
          phonePrefix: '91',
          nationality: 'Indian',
          capital: 'New Delhi',
        },
        {
          iso: 'ID',
          printableName: 'Indonesia',
          phonePrefix: '62',
          nationality: 'Indonesian',
          capital: 'Jakarta',
        },
        {
          iso: 'IR',
          printableName: 'Iran, Islamic Republic of',
          phonePrefix: '98',
          nationality: 'Iranian',
          capital: 'Tehran',
        },
        {
          iso: 'IQ',
          printableName: 'Iraq',
          phonePrefix: '964',
          nationality: 'Iraqi',
          capital: 'Baghdad',
        },
        {
          iso: 'IE',
          printableName: 'Ireland',
          phonePrefix: '353',
          nationality: 'Irish',
          capital: 'Dublin',
        },
        {
          iso: 'IM',
          printableName: 'Isle of Man',
          phonePrefix: '44',
          nationality: 'Manx',
          capital: 'Douglas',
        },
        {
          iso: 'IL',
          printableName: 'Israel',
          phonePrefix: '972',
          nationality: 'Israeli',
          capital: 'Jerusalem',
        },
        {
          iso: 'IT',
          printableName: 'Italy',
          phonePrefix: '39',
          nationality: 'Italian',
          capital: 'Rome',
        },
        {
          iso: 'JM',
          printableName: 'Jamaica',
          phonePrefix: '876',
          nationality: 'Jamaican',
          capital: 'Kingston',
        },
        {
          iso: 'JP',
          printableName: 'Japan',
          phonePrefix: '81',
          nationality: 'Japanese',
          capital: 'Tokyo',
        },
        {
          iso: 'JE',
          printableName: 'Jersey',
          phonePrefix: '44',
          nationality: '',
          capital: 'Saint Helier',
        },
        {
          iso: 'JO',
          printableName: 'Jordan',
          phonePrefix: '962',
          nationality: 'Jordanian',
          capital: 'Amman',
        },
        {
          iso: 'KZ',
          printableName: 'Kazakhstan',
          phonePrefix: '7',
          nationality: 'Kazakhstani',
          capital: 'Nur-Sultan',
        },
        {
          iso: 'KE',
          printableName: 'Kenya',
          phonePrefix: '254',
          nationality: 'Kenyan',
          capital: 'Nairobi',
        },
        {
          iso: 'KI',
          printableName: 'Kiribati',
          phonePrefix: '686',
          nationality: 'I-Kiribati',
          capital: 'Tarawa',
        },
        {
          iso: 'KP',
          printableName: "Korea, Democratic People's Republic of",
          phonePrefix: '850',
          nationality: 'North Korean',
          capital: 'Pyongyang',
        },
        {
          iso: 'KR',
          printableName: 'Korea, Republic of',
          phonePrefix: '82',
          nationality: 'South Korean',
          capital: 'Seoul',
        },
        {
          iso: 'KW',
          printableName: 'Kuwait',
          phonePrefix: '965',
          nationality: 'Kuwaiti',
          capital: 'Kuwait City',
        },
        {
          iso: 'KG',
          printableName: 'Kyrgyzstan',
          phonePrefix: '996',
          nationality: 'Kyrgyzstani',
          capital: 'Bishkek',
        },
        {
          iso: 'LA',
          printableName: "Lao People's Democratic Republic",
          phonePrefix: '856',
          nationality: 'Laotian',
          capital: 'Vientiane',
        },
        {
          iso: 'LV',
          printableName: 'Latvia',
          phonePrefix: '371',
          nationality: 'Latvian',
          capital: 'Riga',
        },
        {
          iso: 'LB',
          printableName: 'Lebanon',
          phonePrefix: '961',
          nationality: 'Lebanese',
          capital: 'Beirut',
        },
        {
          iso: 'LS',
          printableName: 'Lesotho',
          phonePrefix: '266',
          nationality: 'Mosotho',
          capital: 'Maseru',
        },
        {
          iso: 'LR',
          printableName: 'Liberia',
          phonePrefix: '231',
          nationality: 'Liberian',
          capital: 'Monrovia',
        },
        {
          iso: 'LY',
          printableName: 'Libya',
          phonePrefix: '218',
          nationality: 'Libyan',
          capital: 'Tripoli',
        },
        {
          iso: 'LI',
          printableName: 'Liechtenstein',
          phonePrefix: '423',
          nationality: 'Liechtensteiner',
          capital: 'Vaduz',
        },
        {
          iso: 'LT',
          printableName: 'Lithuania',
          phonePrefix: '370',
          nationality: 'Lithuanian',
          capital: 'Vilnius',
        },
        {
          iso: 'LU',
          printableName: 'Luxembourg',
          phonePrefix: '352',
          nationality: 'Luxembourger',
          capital: 'Luxembourg',
        },
        {
          iso: 'MO',
          printableName: 'Macao',
          phonePrefix: '853',
          nationality: 'Macanese',
          capital: 'Macau',
        },
        {
          iso: 'MK',
          printableName: 'Macedonia, the former Yugoslav Republic of',
          phonePrefix: '389',
          nationality: 'Macedonian',
          capital: 'Skopje',
        },
        {
          iso: 'MG',
          printableName: 'Madagascar',
          phonePrefix: '261',
          nationality: 'Malagasy',
          capital: 'Antananarivo',
        },
        {
          iso: 'MW',
          printableName: 'Malawi',
          phonePrefix: '265',
          nationality: 'Malawian',
          capital: 'Lilongwe',
        },
        {
          iso: 'MY',
          printableName: 'Malaysia',
          phonePrefix: '60',
          nationality: 'Malaysian',
          capital: 'Kuala Lumpur',
        },
        {
          iso: 'MV',
          printableName: 'Maldives',
          phonePrefix: '960',
          nationality: 'Maldivian',
          capital: 'Malé',
        },
        {
          iso: 'ML',
          printableName: 'Mali',
          phonePrefix: '223',
          nationality: 'Malian',
          capital: 'Bamako',
        },
        {
          iso: 'MT',
          printableName: 'Malta',
          phonePrefix: '356',
          nationality: 'Maltese',
          capital: 'Valletta',
        },
        {
          iso: 'MH',
          printableName: 'Marshall Islands',
          phonePrefix: '692',
          nationality: 'Marshallese',
          capital: 'Majuro',
        },
        {
          iso: 'MQ',
          printableName: 'Martinique',
          phonePrefix: '596',
          nationality: '',
          capital: 'Fort-de-France',
        },
        {
          iso: 'MR',
          printableName: 'Mauritania',
          phonePrefix: '222',
          nationality: 'Mauritanian',
          capital: 'Nouakchott',
        },
        {
          iso: 'MU',
          printableName: 'Mauritius',
          phonePrefix: '230',
          nationality: 'Mauritian',
          capital: 'Port Louis',
        },
        {
          iso: 'YT',
          printableName: 'Mayotte',
          phonePrefix: '262',
          nationality: '',
          capital: 'Mamoudzou',
        },
        {
          iso: 'MX',
          printableName: 'Mexico',
          phonePrefix: '52',
          nationality: 'Mexican',
          capital: 'Mexico City',
        },
        {
          iso: 'FM',
          printableName: 'Micronesia, Federated States of',
          phonePrefix: '691',
          nationality: 'Micronesian',
          capital: 'Palikir',
        },
        {
          iso: 'MD',
          printableName: 'Moldova, Republic of',
          phonePrefix: '373',
          nationality: 'Moldovan',
          capital: 'Chișinău',
        },
        {
          iso: 'MC',
          printableName: 'Monaco',
          phonePrefix: '377',
          nationality: 'Monacan',
          capital: 'Monaco',
        },
        {
          iso: 'MN',
          printableName: 'Mongolia',
          phonePrefix: '976',
          nationality: 'Mongolian',
          capital: 'Ulaanbaatar',
        },
        {
          iso: 'ME',
          printableName: 'Montenegro',
          phonePrefix: '382',
          nationality: 'Montenegrin',
          capital: 'Podgorica',
        },
        {
          iso: 'MS',
          printableName: 'Montserrat',
          phonePrefix: '664',
          nationality: 'Montserratian',
          capital: 'Plymouth',
        },
        {
          iso: 'MA',
          printableName: 'Morocco',
          phonePrefix: '212',
          nationality: 'Moroccan',
          capital: 'Rabat',
        },
        {
          iso: 'MZ',
          printableName: 'Mozambique',
          phonePrefix: '258',
          nationality: 'Mozambican',
          capital: 'Maputo',
        },
        {
          iso: 'MM',
          printableName: 'Myanmar',
          phonePrefix: '95',
          nationality: 'Burmese',
          capital: 'Naypyidaw',
        },
        {
          iso: 'NA',
          printableName: 'Namibia',
          phonePrefix: '264',
          nationality: 'Namibian',
          capital: 'Windhoek',
        },
        {
          iso: 'NR',
          printableName: 'Nauru',
          phonePrefix: '674',
          nationality: 'Nauruan',
          capital: 'Yaren',
        },
        {
          iso: 'NP',
          printableName: 'Nepal',
          phonePrefix: '977',
          nationality: 'Nepalese',
          capital: 'Kathmandu',
        },
        {
          iso: 'NL',
          printableName: 'Netherlands',
          phonePrefix: '31',
          nationality: 'Dutch',
          capital: 'Amsterdam',
        },
        {
          iso: 'NC',
          printableName: 'New Caledonia',
          phonePrefix: '687',
          nationality: 'New Caledonian',
          capital: 'Nouméa',
        },
        {
          iso: 'NZ',
          printableName: 'New Zealand',
          phonePrefix: '64',
          nationality: 'New Zealander',
          capital: 'Wellington',
        },
        {
          iso: 'NI',
          printableName: 'Nicaragua',
          phonePrefix: '505',
          nationality: 'Nicaraguan',
          capital: 'Managua',
        },
        {
          iso: 'NE',
          printableName: 'Niger',
          phonePrefix: '227',
          nationality: 'Nigerien',
          capital: 'Niamey',
        },
        {
          iso: 'NG',
          printableName: 'Nigeria',
          phonePrefix: '234',
          nationality: 'Nigerian',
          capital: 'Abuja',
        },
        {
          iso: 'NU',
          printableName: 'Niue',
          phonePrefix: '683',
          nationality: 'Niuean',
          capital: 'Alofi',
        },
        {
          iso: 'NF',
          printableName: 'Norfolk Island',
          phonePrefix: '672',
          nationality: '',
          capital: 'Kingston',
        },
        {
          iso: 'MP',
          printableName: 'Northern Mariana Islands',
          phonePrefix: '670',
          nationality: 'Northern Mariana Islander',
          capital: 'Saipan',
        },
        {
          iso: 'NO',
          printableName: 'Norway',
          phonePrefix: '47',
          nationality: 'Norwegian',
          capital: 'Oslo',
        },
        {
          iso: 'OM',
          printableName: 'Oman',
          phonePrefix: '968',
          nationality: 'Omani',
          capital: 'Muscat',
        },
        {
          iso: 'PK',
          printableName: 'Pakistan',
          phonePrefix: '92',
          nationality: 'Pakistani',
          capital: 'Islamabad',
        },
        {
          iso: 'PW',
          printableName: 'Palau',
          phonePrefix: '680',
          nationality: 'Palauan',
          capital: 'Ngerulmud',
        },
        {
          iso: 'PS',
          printableName: 'Palestinian Territory, Occupied',
          phonePrefix: '970',
          nationality: 'Palestinian',
          capital: 'East Jerusalem',
        },
        {
          iso: 'PA',
          printableName: 'Panama',
          phonePrefix: '507',
          nationality: 'Panamanian',
          capital: 'Panama City',
        },
        {
          iso: 'PG',
          printableName: 'Papua New Guinea',
          phonePrefix: '675',
          nationality: 'Papua New Guinean',
          capital: 'Port Moresby',
        },
        {
          iso: 'PY',
          printableName: 'Paraguay',
          phonePrefix: '595',
          nationality: 'Paraguayan',
          capital: 'Asunción',
        },
        {
          iso: 'PE',
          printableName: 'Peru',
          phonePrefix: '51',
          nationality: 'Peruvian',
          capital: 'Lima',
        },
        {
          iso: 'PH',
          printableName: 'Philippines',
          phonePrefix: '63',
          nationality: 'Filipino',
          capital: 'Manila',
        },
        {
          iso: 'PN',
          printableName: 'Pitcairn',
          phonePrefix: '870',
          nationality: '',
          capital: 'Adamstown',
        },
        {
          iso: 'PL',
          printableName: 'Poland',
          phonePrefix: '48',
          nationality: 'Polish',
          capital: 'Warsaw',
        },
        {
          iso: 'PT',
          printableName: 'Portugal',
          phonePrefix: '351',
          nationality: 'Portuguese',
          capital: 'Lisbon',
        },
        {
          iso: 'PR',
          printableName: 'Puerto Rico',
          phonePrefix: '1',
          nationality: 'Puerto Rican',
          capital: 'San Juan',
        },
        {
          iso: 'QA',
          printableName: 'Qatar',
          phonePrefix: '974',
          nationality: 'Qatari',
          capital: 'Doha',
        },
        {
          iso: 'RE',
          printableName: 'Reunion',
          phonePrefix: '262',
          nationality: '',
          capital: 'Saint-Denis',
        },
        {
          iso: 'RO',
          printableName: 'Romania',
          phonePrefix: '40',
          nationality: 'Romanian',
          capital: 'Bucharest',
        },
        {
          iso: 'RU',
          printableName: 'Russian Federation',
          phonePrefix: '7',
          nationality: 'Russian',
          capital: 'Moscow',
        },
        {
          iso: 'RW',
          printableName: 'Rwanda',
          phonePrefix: '250',
          nationality: 'Rwandan',
          capital: 'Kigali',
        },
        {
          iso: 'BL',
          printableName: 'Saint Barthelemy',
          phonePrefix: '590',
          nationality: '',
          capital: 'Gustavia',
        },
        {
          iso: 'SH',
          printableName: 'Saint Helena, Ascension and Tristan da Cunha',
          phonePrefix: '290',
          nationality: '',
          capital: 'Jamestown',
        },
        {
          iso: 'KN',
          printableName: 'Saint Kitts and Nevis',
          phonePrefix: '1',
          nationality: 'Kittitian, Nevisian',
          capital: 'Basseterre',
        },
        {
          iso: 'LC',
          printableName: 'Saint Lucia',
          phonePrefix: '1',
          nationality: 'Saint Lucian',
          capital: 'Castries',
        },
        {
          iso: 'MF',
          printableName: 'Saint Martin (French part)',
          phonePrefix: '590',
          nationality: '',
          capital: 'Marigot',
        },
        {
          iso: 'PM',
          printableName: 'Saint Pierre and Miquelon',
          phonePrefix: '508',
          nationality: '',
          capital: 'Saint-Pierre',
        },
        {
          iso: 'VC',
          printableName: 'Saint Vincent and the Grenadines',
          phonePrefix: '1',
          nationality: 'Saint Vincentian',
          capital: 'Kingstown',
        },
        {
          iso: 'WS',
          printableName: 'Samoa',
          phonePrefix: '685',
          nationality: 'Samoan',
          capital: 'Apia',
        },
        {
          iso: 'SM',
          printableName: 'San Marino',
          phonePrefix: '378',
          nationality: 'San Marinese',
          capital: 'San Marino',
        },
        {
          iso: 'ST',
          printableName: 'Sao Tome and Principe',
          phonePrefix: '239',
          nationality: 'Sao Tomean',
          capital: 'São Tomé',
        },
        {
          iso: 'SA',
          printableName: 'Saudi Arabia',
          phonePrefix: '966',
          nationality: 'Saudi Arabian',
          capital: 'Riyadh',
        },
        {
          iso: 'SN',
          printableName: 'Senegal',
          phonePrefix: '221',
          nationality: 'Senegalese',
          capital: 'Dakar',
        },
        {
          iso: 'RS',
          printableName: 'Serbia',
          phonePrefix: '381',
          nationality: 'Serbian',
          capital: 'Belgrade',
        },
        {
          iso: 'SC',
          printableName: 'Seychelles',
          phonePrefix: '248',
          nationality: 'Seychellois',
          capital: 'Victoria',
        },
        {
          iso: 'SL',
          printableName: 'Sierra Leone',
          phonePrefix: '232',
          nationality: 'Sierra Leonean',
          capital: 'Freetown',
        },
        {
          iso: 'SG',
          printableName: 'Singapore',
          phonePrefix: '65',
          nationality: 'Singaporean',
          capital: 'Singapore',
        },
        {
          iso: 'SX',
          printableName: 'Sint Maarten (Dutch part)',
          phonePrefix: '1',
          nationality: '',
          capital: 'Philipsburg',
        },
        {
          iso: 'SK',
          printableName: 'Slovakia',
          phonePrefix: '421',
          nationality: 'Slovak',
          capital: 'Bratislava',
        },
        {
          iso: 'SI',
          printableName: 'Slovenia',
          phonePrefix: '386',
          nationality: 'Slovenian',
          capital: 'Ljubljana',
        },
        {
          iso: 'SB',
          printableName: 'Solomon Islands',
          phonePrefix: '677',
          nationality: 'Solomon Islander',
          capital: 'Honiara',
        },
        {
          iso: 'SO',
          printableName: 'Somalia',
          phonePrefix: '252',
          nationality: 'Somali',
          capital: 'Mogadishu',
        },
        {
          iso: 'ZA',
          printableName: 'South Africa',
          phonePrefix: '27',
          nationality: 'South African',
          capital: 'Cape Town',
        },
        {
          iso: 'GS',
          printableName: 'South Georgia and the South Sandwich Islands',
          phonePrefix: '500',
          nationality: '',
          capital: 'King Edward Point',
        },
        {
          iso: 'SS',
          printableName: 'South Sudan',
          phonePrefix: '211',
          nationality: 'South Sudanese',
          capital: 'Juba',
        },
        {
          iso: 'ES',
          printableName: 'Spain',
          phonePrefix: '34',
          nationality: 'Spanish',
          capital: 'Madrid',
        },
        {
          iso: 'LK',
          printableName: 'Sri Lanka',
          phonePrefix: '94',
          nationality: 'Sri Lankan',
          capital: 'Colombo',
        },
        {
          iso: 'SD',
          printableName: 'Sudan',
          phonePrefix: '249',
          nationality: 'Sudanese',
          capital: 'Khartoum',
        },
        {
          iso: 'SR',
          printableName: 'Suriname',
          phonePrefix: '597',
          nationality: 'Surinamese',
          capital: 'Paramaribo',
        },
        {
          iso: 'SJ',
          printableName: 'Svalbard and Jan Mayen',
          phonePrefix: '47',
          nationality: '',
          capital: 'Longyearbyen',
        },
        {
          iso: 'SZ',
          printableName: 'Swaziland',
          phonePrefix: '268',
          nationality: 'Swazi',
          capital: 'Mbabane',
        },
        {
          iso: 'SE',
          printableName: 'Sweden',
          phonePrefix: '46',
          nationality: 'Swedish',
          capital: 'Stockholm',
        },
        {
          iso: 'CH',
          printableName: 'Switzerland',
          phonePrefix: '41',
          nationality: 'Swiss',
          capital: 'Bern',
        },
        {
          iso: 'SY',
          printableName: 'Syrian Arab Republic',
          phonePrefix: '963',
          nationality: 'Syrian',
          capital: 'Damascus',
        },
        {
          iso: 'TW',
          printableName: 'Taiwan, Province of China',
          phonePrefix: '886',
          nationality: 'Taiwanese',
          capital: 'Taipei',
        },
        {
          iso: 'TJ',
          printableName: 'Tajikistan',
          phonePrefix: '992',
          nationality: 'Tajikistani',
          capital: 'Dushanbe',
        },
        {
          iso: 'TZ',
          printableName: 'United Republic of Tanzania',
          phonePrefix: '255',
          nationality: 'Tanzanian',
          capital: 'Dodoma',
        },
        {
          iso: 'TH',
          printableName: 'Thailand',
          phonePrefix: '66',
          nationality: 'Thai',
          capital: 'Bangkok',
        },
        {
          iso: 'TL',
          printableName: 'Timor-Leste',
          phonePrefix: '670',
          nationality: 'Timorese',
          capital: 'Dili',
        },
        {
          iso: 'TG',
          printableName: 'Togo',
          phonePrefix: '228',
          nationality: 'Togolese',
          capital: 'Lomé',
        },
        {
          iso: 'TK',
          printableName: 'Tokelau',
          phonePrefix: '690',
          nationality: '',
          capital: 'Fakaofo',
        },
        {
          iso: 'TO',
          printableName: 'Tonga',
          phonePrefix: '676',
          nationality: 'Tongan',
          capital: "Nuku'alofa",
        },
        {
          iso: 'TT',
          printableName: 'Trinidad and Tobago',
          phonePrefix: '1',
          nationality: 'Trinidadian, Tobagonian',
          capital: 'Port of Spain',
        },
        {
          iso: 'TN',
          printableName: 'Tunisia',
          phonePrefix: '216',
          nationality: 'Tunisian',
          capital: 'Tunis',
        },
        {
          iso: 'TR',
          printableName: 'Turkey',
          phonePrefix: '90',
          nationality: 'Turkish',
          capital: 'Ankara',
        },
        {
          iso: 'TM',
          printableName: 'Turkmenistan',
          phonePrefix: '993',
          nationality: 'Turkmen',
          capital: 'Ashgabat',
        },
        {
          iso: 'TC',
          printableName: 'Turks and Caicos Islands',
          phonePrefix: '1',
          nationality: '',
          capital: 'Cockburn Town',
        },
        {
          iso: 'TV',
          printableName: 'Tuvalu',
          phonePrefix: '688',
          nationality: 'Tuvaluan',
          capital: 'Funafuti',
        },
        {
          iso: 'UG',
          printableName: 'Uganda',
          phonePrefix: '256',
          nationality: 'Ugandan',
          capital: 'Kampala',
        },
        {
          iso: 'UA',
          printableName: 'Ukraine',
          phonePrefix: '380',
          nationality: 'Ukrainian',
          capital: 'Kyiv',
        },
        {
          iso: 'AE',
          printableName: 'United Arab Emirates',
          phonePrefix: '971',
          nationality: 'Emirati',
          capital: 'Abu Dhabi',
        },
        {
          iso: 'GB',
          printableName: 'United Kingdom',
          phonePrefix: '44',
          nationality: 'British',
          capital: 'London',
        },
        {
          iso: 'US',
          printableName: 'United States Of America',
          phonePrefix: '1',
          nationality: 'American',
          capital: 'Washington, D.C.',
        },
        {
          iso: 'UY',
          printableName: 'Uruguay',
          phonePrefix: '598',
          nationality: 'Uruguayan',
          capital: 'Montevideo',
        },
        {
          iso: 'UZ',
          printableName: 'Uzbekistan',
          phonePrefix: '998',
          nationality: 'Uzbekistani',
          capital: 'Tashkent',
        },
        {
          iso: 'VU',
          printableName: 'Vanuatu',
          phonePrefix: '678',
          nationality: 'Ni-Vanuatu',
          capital: 'Port Vila',
        },
        {
          iso: 'VE',
          printableName: 'Venezuela, Bolivarian Republic of',
          phonePrefix: '58',
          nationality: 'Venezuelan',
          capital: 'Caracas',
        },
        {
          iso: 'VN',
          printableName: 'Viet Nam',
          phonePrefix: '84',
          nationality: 'Vietnamese',
          capital: 'Hanoi',
        },
        {
          iso: 'VG',
          printableName: 'Virgin Islands, British',
          phonePrefix: '1',
          nationality: 'British Virgin Islander',
          capital: 'Road Town',
        },
        {
          iso: 'VI',
          printableName: 'Virgin Islands, U.S.',
          phonePrefix: '1',
          nationality: 'U.S. Virgin Islander',
          capital: 'Charlotte Amalie',
        },
        {
          iso: 'WF',
          printableName: 'Wallis and Futuna',
          phonePrefix: '681',
          nationality: '',
          capital: 'Mata-Utu',
        },
        {
          iso: 'EH',
          printableName: 'Western Sahara',
          phonePrefix: '212',
          nationality: 'Sahrawi',
          capital: 'El Aaiún',
        },
        {
          iso: 'YE',
          printableName: 'Yemen',
          phonePrefix: '967',
          nationality: 'Yemeni',
          capital: 'Sana\'a',
        },
        {
          iso: 'ZM',
          printableName: 'Zambia',
          phonePrefix: '260',
          nationality: 'Zambian',
          capital: 'Lusaka',
        },
        {
          iso: 'ZW',
          printableName: 'Zimbabwe',
          phonePrefix: '263',
          nationality: 'Zimbabwean',
          capital: 'Harare',
        },
      ],
    };
  }

  async getSettings(): Promise<any> {
    return await this.partnerTypeRepository.find();
  }
}
