export enum RoleEnum {
  'super_admin' = 1,
  'client' = 2,
  'user_admin' = 3,
  'partner' = 4,
  'sales_manager' = 5,
  'sales_agent' = 6,
  'marketing_manager' = 7,
  'marketing_specialist' = 8,
  'backoffice_manager' = 9,
  'backoffice_specialist' = 10,
  'finance_manager' = 11,
  'finance_specialist' = 12,
  'office_manager' = 13,
  'retention_agent' = 14,
  'retention_manager' = 15,
  'support_manager' = 16,
  'support_agent' = 17,
  'compliance_specialist' = 18,
  'compliance_manager' = 19,
}
